### ISSUE TITLE
Failed to read account password contents 

### ISSUE THREAD

**Issue by nikhilupadhyay1709** [ConsenSys/quorum#1254]
#### System information

Geth version: ` 1.10.8-stable
                       Git Commit: 26675454bf93bf904be7a43cce6b3f550115ff90
                        Architecture: amd64
                        Go Version: go1.16.4
                        Operating System: linux
                        GOPATH=/home/nikhil/go_projects
                        GOROOT=go`

OS & Version: Linux

Branch, Commit Hash or Release: `main branch`

#### Steps to reproduce the behavior  build the faucet part code in golang microservises

can anyone help me with it or not 
````

**Comment by antonydenyer** [comment]
Duplicate https://github.com/ethereum/go-ethereum/issues/23582
