### ISSUE TITLE
Error 404 Adding-removing-IBFT-validators 

### ISSUE THREAD

**Issue by saturnino84** [ConsenSys/quorum#1258]
Hello. 

Can't access to  https://docs.goquorum.consensys.net/en/stable/Tutorials/Adding-removing-IBFT-validators/

**Comment by bgravenorst** [comment]
Thanks for raising this, the page has been moved to https://docs.goquorum.consensys.net/en/stable/Tutorials/Private-Network/Adding-removing-IBFT-validators/

I'll raise an issue to add a redirect to the new location.

**Comment by baptiste-b-pegasys** [comment]
https://consensys.net/docs/goquorum/en/latest/tutorials/private-network/adding-removing-ibft-validators/
