### ISSUE TITLE
Upgrade from Quorum 2.6 to 21.7

### ISSUE THREAD

**Issue by subhasisbanik** [ConsenSys/quorum#1267]
I am trying to upgrade my existing Quorum network with data from v2.6 to v21.7. 
I found the documentation to upgrade to v2.6 

https://docs.goquorum.consensys.net/en/stable/GetStarted/migration/ 

but did not find anything for upgrading from v2.6 to v21.7.
Any documentation available?

Thanks in advance

**Comment by ricardolyn** [comment]
Hey @subhasisbanik. no migration should be needed to that version. However, I recommend checking the release notes [here](https://github.com/ConsenSys/quorum/releases) to make sure you understand as there are some breaking changes in some versions.

**Comment by subhasisbanik** [comment]
Hey @ricardolyn  we want to use the multitenancy support that is introduced in v21.7.
Are there any breaking changes introduced which prevents the upgrade from v2.6 to v21.7?

**Comment by achraf17** [comment]
Hey @subhasisbanik,
The quorum version v2.6.0 is based on the geth version v1.9.7.
The quorum version v21.7.1 is based on the geth version v1.9.24.
Taking that into consideration you need to check if there are any breaking changes from v1.9.7 to v1.9.24 from geth perspective. here is a [link](https://github.com/ethereum/go-ethereum/releases?after=v1.9.25) to the release notes.
Also here is the documentation [link](https://docs.goquorum.consensys.net/en/latest/Concepts/Multitenancy/MultiplePrivateStates/#upgrading-a-node-to-mps) how to upgrading a node to MPS with [migration guide](https://docs.goquorum.consensys.net/en/latest/Concepts/Multitenancy/MultiplePrivateStates/#migration-guides)

**Comment by subhasisbanik** [comment]
@achraf17  Thanks for your reply and the documentation.
I am trying to get hold of a document which mentions the upgradation steps of a quorum node as a whole from v2.6.0 to v21.7. Could you please help me here?

**Comment by achraf17** [comment]
@subhasisbanik There is no single document that state the migration from v2.6.0 to v21.7 directly, as usually user will migrate from a version to the next one.

**Comment by subhasisbanik** [comment]
@achraf17  So how should I upgrade from v2.6.0? Will that be to v2.7 and then to v20.10?

**Comment by achraf17** [comment]
@subhasisbanik You can migrate directly but you need to check what i mentioned before in this [comment](https://github.com/ConsenSys/quorum/issues/1267#issuecomment-938567558)

**Comment by subhasisbanik** [comment]
Hi @achraf17 thanks for your reply. I tried to update with the link provided by you in the previous comment but as mentioned in https://docs.goquorum.consensys.net/en/latest/Concepts/Multitenancy/MultiplePrivateStates/#goquorum
I am not able find any example for isMPS in the genesis.json. Moreover, the tutorial in https://docs.goquorum.consensys.net/en/21.7.1/Tutorials/Private-Network/Create-a-Raft-network/ does not mention anything about isMPS variable in the genesis.json
Also, since I am already having a network with v2.6.0, I tried to run geth mpsdbuppgrade --datadir data as mentioned in https://docs.goquorum.consensys.net/en/latest/Concepts/Multitenancy/MultiplePrivateStates/#goquorum_1
but it throws error. 
Could you please let me know if I am going wrong anywhere in the migration steps?

**Comment by achraf17** [comment]
Hello @subhasisbanik, 
You can find a network example on [quorum-examples](https://github.com/ConsenSys/quorum-examples) on the [docker-compose](https://github.com/ConsenSys/quorum-examples/blob/master/docker-compose-4nodes-mps.yml) file, the genesis.json will look like 
```
{
  "coinbase": "0x0000000000000000000000000000000000000000",
  "config": {
    "homesteadBlock": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "chainId": 10,
    "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "qip714Block": 50,
    "isQuorum": true,
    "privacyPrecompileBlock": 0,
    "maxCodeSizeConfig": [
      {
        "block": 0,
        "size": 64
      }
    ],
    "istanbul": {
      "epoch": 30000,
      "policy": 0,
      "ceil2Nby3Block": 0
    },
    "isMPS": true
  },
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000f89af85494d8dba507e85f116b1f7e231ca8525fc9008a6966946571d97f340c8495b661a823f2c2145ca47d63c294e36cbeb565b061217930767886474e3cde903ac594f512a992f3fb749857d758ffda1330e590fa915eb8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0",
  "gasLimit": "0xE0000000",
  "difficulty": "0x1",
  "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "nonce": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}
``` 
Can you share the error that you got after running `geth mpsdbupgrade --datadir` ?

**Comment by subhasisbanik** [comment]
Hi @achraf17 thanks for detail. I have prepared the binary from the link below:

https://github.com/ConsenSys/quorum.git --branch v21.7.0

And below is the geth -h command response which shows that there is no property, "mspdbupgrade" in the geth binary:

![image](https://user-images.githubusercontent.com/25420904/138108620-c3e77140-84bb-4c08-a30b-ef0ec721d267.png)

Also, I am already running a network on v2.6.0 with 1000 existing transactions. Will changing the genesis.json file perform the upgrade to accepting MPS?

**Comment by subhasisbanik** [comment]
Hi @achraf17 or @bgravenorst any update on this? I am stuck at this point of the setup.

**Comment by achraf17** [comment]
hi @subhasisbanik,
Can you use the latest version from master branch, that should have the `mspdbupgrade` command. Also use master to run the nodes. In the meantime, we should release a newer version that would include that.

**Comment by subhasisbanik** [comment]
Hi @achraf17 , Thanks for the update.

I am able to run the geth mspdbupdgrade command now.

But now I am facing issue with Tessera 21.7.2 where I have updated the config file as below but I am not able to run the tessera node with this config.json :

{
   "useWhiteList": false,
   "jdbc": {
       "username": "sa",
       "password": "",
       "url": "jdbc:h2://home/quorum-network/new-node-1tb/db1;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
       "autoCreateTables": true
   },
   "serverConfigs":[
       {
           "app":"ThirdParty",
           "enabled": true,
           "serverAddress": "http://localhost:9081",
           "communicationType" : "REST"
       },
       {
           "app":"Q2T",
           "enabled": true,
            "serverAddress":"unix:/home/quorum-network/new-node-1tb/tm.ipc",
            "communicationType" : "REST"
       },
       {
           "app":"P2P",
           "enabled": true,
           "serverAddress":"http://localhost:9001",
           "sslConfig": {
               "tls": "OFF"
           },
           "communicationType" : "REST"
       }
   ],
   "peer": [
       {
           "url": "http://localhost:9001"
       },
       {
           "url": "http://localhost:9003"
       }
   ],
   "keys": {
       "passwords": [],
       "keyData": [
           {
               "config": "/home/quorum-network/new-node-1tb/new-node-1a.key",
               "publicKey": "/home/quorum-network/new-node-1tb/new-node-1a.pub"
           },
           {
               "config": "/home/quorum-network/new-node-1tb/new-node-1b.key",
               "publicKey": "/home/quorum-network/new-node-1tb/new-node-1b.pub"
           }
       ]
   },
   "alwaysSendTo": [],
   "residentGroups":[
    {
      "name":"PS1",
      "description":"Privacy Group 1",
      "members":["7rGB7lysfgoOoiO5xLhXsNEiGpOPAqeUQljcwgFoTwk="]
    },
    {
      "name":"PS2",
      "description":"Privacy Group 2",
      "members":["2JGG5J7jp3dCoCbX82ppP3Ye9veADrJBBcG1J72jwUs="]
    }
  ],
  "features": {
    "enableMultiplePrivateStates": "true"
  }
}



Below is the error received while trying to run:

2021-10-25 14:55:07.354 [main] INFO  c.q.t.enclave.EnclaveFactoryImpl - Creating enclave
2021-10-25 14:55:07.357 [main] INFO  c.q.t.enclave.EnclaveFactoryImpl - Creating enclave server
2021-10-25 14:55:07.361 [main] ERROR c.q.t.enclave.EnclaveFactoryImpl -
java.lang.IllegalArgumentException: Illegal base64 character 2d
        at java.base/java.util.Base64$Decoder.decode0(Base64.java:746)
        at java.base/java.util.Base64$Decoder.decode(Base64.java:538)
        at java.base/java.util.Base64$Decoder.decode(Base64.java:561)
        at tessera.enclave.api@21.7.2/com.quorum.tessera.enclave.KeyPairConverter.convert(KeyPairConverter.java:101)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at tessera.enclave.api@21.7.2/com.quorum.tessera.enclave.KeyPairConverter.convert(KeyPairConverter.java:30)
        at tessera.enclave.api@21.7.2/com.quorum.tessera.enclave.EnclaveFactoryImpl.createServer(EnclaveFactoryImpl.java:64)
        at tessera.enclave.api@21.7.2/com.quorum.tessera.enclave.EnclaveFactoryImpl.createEnclave(EnclaveFactoryImpl.java:44)
        at tessera.enclave.api@21.7.2/com.quorum.tessera.enclave.EnclaveProvider.provider(EnclaveProvider.java:24)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.base/java.util.ServiceLoader$ProviderImpl.invokeFactoryMethod(ServiceLoader.java:737)
        at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:720)
        at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
        at java.base/java.util.ServiceLoader.findFirst(ServiceLoader.java:1810)
        at tessera.enclave.api@21.7.2/com.quorum.tessera.enclave.Enclave.create(Enclave.java:127)
        at tessera.application@21.7.2/com.quorum.tessera.launcher.Main.main(Main.java:77)
com.quorum.tessera.enclave.Enclave: public static com.quorum.tessera.enclave.Enclave com.quorum.tessera.enclave.EnclaveProvider.provider() failed
java.lang.IllegalArgumentException: Illegal base64 character 2d

Could you please help let me know where I am going wrong in this?

**Comment by achraf17** [comment]
@subhasisbanik at first glance the url looks not right it has two `//` better double check that
`"url": "jdbc:h2://home/quorum-network/new-node-1tb/db1;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",`
In terms of the `Illegal base64 character 2d` error, most probably its a formatting issue, extra character...

**Comment by achraf17** [comment]
Closing this, feel free to reopen.

**Comment by subhasisbanik** [comment]
Yes sure @achraf17 . It worked with the updated config.json file for tessera. I might have couple more questions, which I will open new thread. Thanks for all your help.
