### ISSUE TITLE
Revert reason not returned when PrivacyFlag set to 3. Working with public txns or when privacyFlag is set 0.

### ISSUE THREAD

**Issue by melvinjtomy** [ConsenSys/quorum#1270]
#### System information
Quorum Docker Container (v21.7.0) deployed to Azure Kubernetes Service. Ubuntu nodes. 

#### Expected behaviour
Should see revert reason.

#### Actual behaviour
Getting the below error response
---
Error: Returned error: execution reverted
...
...
...
cookies\dist\xml-http-request.js:289:61)
at IncomingMessage.emit (events.js:412:35)
at endReadableNT (internal/streams/readable.js:1317:12)
at processTicksAndRejections (internal/process/task_queues.js:82:21) {
data: null
}
---
#### Steps to reproduce the behaviour
pass the privacyFlag attribute as 3, in Contract.methods.<method-name>().send({from:account, gasPrice: 0,gas: 700000000, privateFor:activePG, privacyFlag: 3})

**Comment by MadelineMurray** [comment]
Thanks for raising - we'll be investigating this in our next sprint.

**Comment by baptiste-b-pegasys** [comment]
We have reproduced the behavior and discussed of the best solution. The issue is in our backlog.

**Comment by melvinjtomy** [comment]
> We have reproduced the behavior and discussed of the best solution. The issue is in our backlog.

By when can we expect this to be completed?

**Comment by baptiste-b-pegasys** [comment]
A proposed fix has been discussed, which is to continue the transaction even if the simulation run fails, to have the revert reason.

But because it's with the privacy enhancement, the simulation is warranty that the transaction will succeed and it is preferable not to create a failed transaction in the blockchain.

The plan is to have the revert reason from the simulation run, and this is planned after the upgrade of geth is done.

**Comment by baptiste-b-pegasys** [comment]
https://github.com/baptiste-b-pegasys/quorum/pull/28

**Comment by ghost** [comment]
@baptiste-b-pegasys 
Which Quorum Docker Container version has the fix applied?

**Comment by baptiste-b-pegasys** [comment]
Hi,
It's not released yet, it's been committed after the geth 1.10 merge.
You can build from master the Docker file.
