### ISSUE TITLE
Quorum node not getting started with Multitenancy flag

### ISSUE THREAD

**Issue by Purbaja** [ConsenSys/quorum#1271]
Trying to setup a multitenant quorum node with version 21.7.1.
Tessera is setup with version 21.7.2 and MPS feature is also enabled.

Followed the quorum example's "docker-compose-4nodes-mt.yml" file tried to setup the multitenant quorum node. But while starting the Quorum node (Node1) with --multitenancy option, the Quorum Node1 is not getting started.  Other nodes (without multitenancy flag) are getting up and running.

Log from quorum node1 -

JQ Update Query: .config.isMPS = true
{
  "alloc": {
    "0xed9d02e382b34818e88b88a309c7fe71e65f419d": {
      "balance": "1000000000000000000000000000"
    },
    "0xca843569e3427144cead5e4d5999a3d0ccf92b8e": {
      "balance": "1000000000000000000000000000"
    },
    "0x0fbdc686b912d7722dc86510934589e0aaf3b55a": {
      "balance": "1000000000000000000000000000"
    },
    "0x9186eb3d20cbd1f5f992a950d808c4495153abd5": {
      "balance": "1000000000000000000000000000"
    },
    "0x0638e1574728b6d862dd5d3a3e0942c3be47d996": {
      "balance": "1000000000000000000000000000"
    }
  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "config": {
    "homesteadBlock": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "chainId": 10,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip158Block": 0,
    "qip714Block": 20,
    "isQuorum": true,
    "privacyPrecompileBlock": 0,
    "maxCodeSizeConfig": [
      {
        "block": 0,
        "size": 64
      }
    ],
    "isMPS": true
  },
  "difficulty": "0x0",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0xE0000000",
  "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
  "nonce": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}
INFO [10-28|12:03:41.024] Connecting to private tx manager using IPC socket
INFO [10-28|12:03:41.084] Tessera API version: 3.0
INFO [10-28|12:03:41.084] Target Private Tx Manager                name=Tessera distributionVersion=21.7.2
INFO [10-28|12:03:41.086] Maximum peer count                       ETH=50 LES=0 total=50
INFO [10-28|12:03:41.086] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
ERROR[10-28|12:03:41.087] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-28|12:03:41.087] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-28|12:03:41.087] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-28|12:03:41.087] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-28|12:03:41.088] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-28|12:03:41.088] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
WARN [10-28|12:03:41.088] Found deprecated node list file /qdata/dd/static-nodes.json, please use the TOML config file instead.

Please guide for this error.

**Comment by subhasisbanik** [comment]
@achraf17 could you please help on this?

**Comment by achraf17** [comment]
Hello @Purbaja, 
The error that i am seeing in the shared logs are not relating to the multi-tenancy its relating to the USB hardware which you can disable using `--nousb`.
Can share the complete logs of node 1

**Comment by Purbaja** [comment]
Hi @achraf17 ,

PFA the complete log of node 1 -
[Quorum Node1 Log.txt](https://github.com/ConsenSys/quorum/files/7453575/Quorum.Node1.Log.txt)

**Comment by subhasisbanik** [comment]
@achraf17  could you help in this?

**Comment by achraf17** [comment]
Hi @Purbaja,
After looking at the complete log, I dont see anything that is wrong with node
* the http server is running fine with the available APIs:
```
ERROR[11-01|13:26:50.749] Unavailable modules in HTTP API list     unavailable="[shh quorum]" available="[admin debug web3 eth txpool personal ethash miner net raft quorumExtension]"
INFO [11-01|13:26:50.751] HTTP server started                      endpoint=[::]:8545 cors=* vhosts=* isTls=true
```
* the raft server is running fine as well:
```
INFO [11-01|13:26:50.772] raft node started
```
* Also able to elect leader for the cluster:
```
raft2021/11/01 13:26:50.839190 INFO: raft.node: 1 elected leader 3 at term 4
```

Have you tried submitting few transactions to the network ? here is an [example](https://github.com/ConsenSys/quorum-examples/blob/master/examples/7nodes/MultitenancyAndMultiplePrivateStates.md#multitenancy-with-multiple-private-states) how to do so, let me know how it goes.

**Comment by Purbaja** [comment]
Hi @achraf17 , the quorum node1 is not becoming healthy. So, not able to attach geth and perform any transaction.

**Comment by achraf17** [comment]
Hi @Purbaja,
You can ignore the health check `unhealthy` as health check command is not passing an access token to the rpc server which is being reject by the auth plugin. I have created an [issue](https://github.com/ConsenSys/quorum-examples/issues/269) for the matter.

Nevertheless, you can still attach to the console by running `./mtAttachWithPSI.sh PS1` just make sure that your [geth version](https://github.com/ConsenSys/quorum-examples/blob/master/examples/7nodes/mtAttachWithPSI.sh#L19) is `Quorum Version: 21.7.1`
This is my execution log:
```
➜  7nodes git:(master) ✗ ./mtAttachWithPSI.sh PS1
PSI=PS1
node.eoa=0x0
{
  "client_id": "PS1",
  "client_name": "",
  "client_secret": "foofoo",
  "redirect_uris": null,
  "grant_types": [
    "client_credentials"
  ],
  "response_types": null,
  "scope": "rpc://eth_* rpc://quorumExtension_* rpc://rpc_modules psi://PS1?self.eoa=0x0&node.eoa=0x0",
  "audience": [
    "Node1"
  ],
  "owner": "",
  "policy_uri": "",
  "allowed_cors_origins": null,
  "tos_uri": "",
  "client_uri": "",
  "logo_uri": "",
  "contacts": null,
  "client_secret_expires_at": 0,
  "subject_type": "public",
  "token_endpoint_auth_method": "client_secret_post",
  "userinfo_signed_response_alg": "none",
  "created_at": "2021-11-03T09:34:00Z",
  "updated_at": "2021-11-03T09:34:00Z"
}
WARNING: call to admin.getNodeInfo() failed, unable to determine consensus mechanism
Welcome to the Geth JavaScript console!

 modules: admin:1.0 debug:1.0 eth:1.0 istanbul:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

To exit, press ctrl-d
> eth.accounts
["0xed9d02e382b34818e88b88a309c7fe71e65f419d", "0x0638e1574728b6d862dd5d3a3e0942c3be47d996", "0xae9bc6cd5145e67fbd1887a5145271fd182f0ee7", "0xcc71c7546429a13796cf1bf9228bff213e7ae9cc"]
> eth.blockNumber
3958
```

**Comment by Purbaja** [comment]
Hi @achraf17 ,

I ran the quorum 7nodes example with multitenancy enabled -

docker containers:

CONTAINER ID   IMAGE                              COMMAND                   CREATED        STATUS                    PORTS                                                                                               NAMES
74707c56190b   quorumengineering/quorum:21.7.1    "/bin/sh -c 'apk add…"    46 hours ago   Up 46 hours **(unhealthy)**   8546/tcp, 21000/tcp, 30303/tcp, 50400/tcp, 30303/udp, 0.0.0.0:22000->8545/tcp, :::22000->8545/tcp   **quorum-examples_node1_1**
a7d709deaf56   quorumengineering/quorum:21.7.1    "/bin/sh -c 'apk add…"    46 hours ago   Up 46 hours (healthy)     8546/tcp, 21000/tcp, 30303/tcp, 50400/tcp, 30303/udp, 0.0.0.0:22002->8545/tcp, :::22002->8545/tcp   quorum-examples_node3_1
e4b3c0be9bfc   quorumengineering/quorum:21.7.1    "/bin/sh -c 'apk add…"    46 hours ago   Up 46 hours (healthy)     8546/tcp, 21000/tcp, 30303/tcp, 50400/tcp, 30303/udp, 0.0.0.0:22001->8545/tcp, :::22001->8545/tcp   quorum-examples_node2_1
d2b472df405a   quorumengineering/quorum:21.7.1    "/bin/sh -c 'apk add…"    46 hours ago   Up 46 hours (healthy)     8546/tcp, 21000/tcp, 30303/tcp, 50400/tcp, 30303/udp, 0.0.0.0:22003->8545/tcp, :::22003->8545/tcp   quorum-examples_node4_1
b21276d022c7   quorumengineering/tessera:21.7.2   "/bin/sh -c 'if [ \"$…"   46 hours ago   Up 46 hours (healthy)     9000/tcp, 0.0.0.0:9083->9080/tcp, :::9083->9080/tcp                                                 quorum-examples_txmanager3_1
772e9a35e358   oryd/hydra:v1.3.2-alpine           "hydra serve all"         46 hours ago   Up 46 hours               0.0.0.0:4444-4445->4444-4445/tcp, :::4444-4445->4444-4445/tcp                                       multi-tenancy-oauth2-server
f7635345eb4d   quorumengineering/tessera:21.7.2   "/bin/sh -c 'if [ \"$…"   46 hours ago   Up 46 hours (healthy)     9000/tcp, 0.0.0.0:9082->9080/tcp, :::9082->9080/tcp                                                 quorum-examples_txmanager2_1
df475c1211c8   quorumengineering/tessera:21.7.2   "/bin/sh -c 'if [ \"$…"   46 hours ago   Up 46 hours (healthy)     9000/tcp, 0.0.0.0:9081->9080/tcp, :::9081->9080/tcp                                                 quorum-examples_txmanager1_1
9a1cf07a20c3   quorumengineering/tessera:21.7.2   "/bin/sh -c 'if [ \"$…"   46 hours ago   Up 46 hours (healthy)     9000/tcp, 0.0.0.0:9084->9080/tcp, :::9084->9080/tcp                                                 quorum-examples_txmanager4_1


Then i tried running the "./mtAttachWithPSI.sh PS1", but it is giving error -

PSI=PS1
node.eoa=0x0
./mtAttachWithPSI.sh: line 15: jq: command not found
(23) Failed writing body
./mtAttachWithPSI.sh: line 17: jq: command not found
(23) Failed writing body
./mtAttachWithPSI.sh: line 19: geth: command not found

**Comment by achraf17** [comment]
hi @Purbaja,
You need install `jq` and `geth`
[jq install link](https://stackoverflow.com/questions/33184780/install-jq-json-processor-on-ubuntu-10-04)
[quorum binaries](https://github.com/ConsenSys/quorum/releases/tag/v21.7.1)

**Comment by Purbaja** [comment]
Thanks @achraf17 .Through "mtAttachWithPSI.sh" I am able to connect the geth.

**Comment by achraf17** [comment]
Great to hear that @Purbaja, closing this issue, feel free to re/open the issue for more help.
