### ISSUE TITLE
Clef : As an external signer `account_signTransaction` failing to sign raw tx needed for `eth_sendRawPrivateTransaction`

### ISSUE THREAD

**Issue by hammerstrike** [ConsenSys/quorum#1275]
### Quorum network
- Followed [Quorum Developer Quickstart](https://docs.goquorum.consensys.net/en/stable/Tutorials/Quorum-Dev-Quickstart/Using-the-Quickstart/#use-quorum-developer-quickstart) to create and spin up quorum network.
- Deployed private contract using `private_tx.js` created by Quorum Developer Quickstart.

### Clef Service
- Initialized clef service as mentioned in [tutorial.md](https://github.com/ConsenSys/quorum/blob/master/cmd/clef/tutorial.md#initializing-clef)
- Created one account using clef and set [advanced rules](https://github.com/ConsenSys/quorum/blob/master/cmd/clef/tutorial.md#advanced-rules)
- Started clef service with following command
`clef --http --rules rules.js --keystore ../node1/data/keystore --chainid 1337`
![image](https://user-images.githubusercontent.com/5867518/140607170-bd00a89a-ce59-4bff-8255-2168880b0d24.png)

### Using clef as As an external signer to sign tx
[Reference link](https://docs.goquorum.consensys.net/en/21.1.0/HowTo/ManageKeys/clef/#as-an-external-signer)
[Code reference](https://gist.github.com/hammerstrike/f9f104494009f32e220b3002cf88a350)

Steps followed

1. Tessera API `/storeraw`
```
const web3 = new Web3('<CLIENT_URL>')
const contractInstance = new web3.eth.Contract(<ABI>, <CONTRACT_ADDRESS>);
const payload = contractInstance.methods.set(<INPUT_VALUE>).encodeABI();
...

{
    method: 'POST',
    url: `<TESSERA_HOST>/storeraw`,
    headers: { 'Content-Type': 'application/json' },
    data: {
        payload,
        from: publicKey
    }
};

```
Returns
```
{ key: '<HASH_VALUE>'}
```

2. Clef API `account_signTransaction` 

```
const data = web3.utils.toHex(HASH_VALUE)

{
    method: 'POST',
    url: <CLEF_SERVICE_URL>,
    headers: { 'Content-Type': 'application/json' },
    data: {
        id: 2,
        jsonrpc: '2.0',
        method: 'account_signTransaction',
        params: [
            {
                from: clefAccountAddress,
                to: deployedContractAddress,
                gasPrice: "0x0",
                isPrivate: true,
                data
            }
        ]
    }
}

```

Returns an error
`validation failed: Transaction data is not valid ABI (length should be a multiple of 32 (was 84)),Transaction contains data, but the ABI signature could not be found: signature 6e433442 not found`

**Comment by srinivasansankaran** [comment]
Tried to reproduce the issue. Its working fine for me when tried to use web3jsquorum library. Also made it work with /storeRaw API by doing base64 encoding before sending it to tessera.

**Comment by hammerstrike** [comment]
Working with `web3js-quorum.ptm.storeRaw` 

```
const data = contractInstance.methods.set(value).encodeABI();
const txHash = await web3quorum.ptm.storeRaw({
     data,
     privateFrom,
 });
...
```
using `data: '0x'+txHash` in `account_signTransaction`.

thanks @srinivasansankaran
