### ISSUE TITLE
RAFT: Multiple minters and no blocks produced under load

### ISSUE THREAD

**Issue by vdamle** [ConsenSys/quorum#1282]
#### System information

Geth version: `Geth/v1.9.20-stable-dfccc9ac(quorum-v21.4.2)/linux-amd64/go1.13.15`

OS & Version: Linux

Branch, Commit Hash or Release: `commit 1d7926a19a1e7093d11ef996e6d66da3dda79eed (HEAD -> v21.4.2, tag: v21.4.2)`

Consensus Type: RAFT

Network Size: 7 nodes

#### Expected behaviour

When an active minter receives a `MsgVote` at a higher term from a follower, it loses it's leader role and votes for the follower. The follower takes over as minter if it receives enough votes. After this, the old minter should assume the role of a follower and stop producing blocks.
#### Actual behaviour

In a chain running RAFT at a steady state and processing a high number of transactions per second, we've observed the following intermittently:

*  an active Minter producing blocks (`node-3, raft_id: 3`) receives a `MsgVote` from another node (`node-5, raft_id: 5`) at a higher term.
* The minter indicates that it became a `follower` at the incoming message term.
* The minter sends a `Reject` response to the `MsgVote` because it's Raft log is not up to date (it has a raft log with the same index as the incoming message, but at a lower term).
* As part of the `stepFollower` flow, the minter reports conflicts when appending log entries.
* Minter (`node-3`) reports that it has elected `node-5` as leader.
* The new minter `node-5` reports that it has received enough votes to take over and assumes minter role and starts producing blocks.
* The now defunct minter `node-3`, syncs _some_ blocks which are produced by `node-5` and then stops syncing.
* The defunct minter `node-3` then logs that it is `Generating a new block`, which is also indicative that it has still not given up it's minter role. `raft.role` also shows it's status as `minter`.
* `node-5` continues to mine blocks for a while until it's txpool is empty and then the chain stops producing blocks. Meanwhile, the transaction pool in `node-3` continues to grow and it is lagging behind the rest of the chain as well.

It is unclear if the Ring Channel in `node-3` is receiving the `NOT_LEADER` event (and/or if `handleRoleChange()` is getting invoked). We do not have Checkpoints enabled, so we are unable to see those logs in the customer environments where this occurs.

```
raft2021/12/13 23:45:34.772711 INFO: 3 [term: 740] received a MsgVote message with higher term from 5 [term: 741]
raft2021/12/13 23:45:34.772729 INFO: 3 became follower at term 741
raft2021/12/13 23:45:34.772736 INFO: 3 [logterm: 740, index: 9767276, vote: 0] rejected MsgVote from 5 [logterm: 740, index: 9767275] at term 741
raft2021/12/13 23:45:34.772750 INFO: raft.node: 3 lost leader 3 at term 741
raft2021/12/13 23:45:34.845579 INFO: found conflict at index 9767276 [existing term: 740, conflicting term: 741]
raft2021/12/13 23:45:34.845602 INFO: replace the unstable entries from index 9767276
raft2021/12/13 23:45:34.845607 INFO: raft.node: 3 elected leader 5 at term 741
```

#### Steps to reproduce the behavior

We do not know of a definitely way to reproduce this, except, this occurs when a RAFT chain is operating at a fairly high transactions per second.

#### Backtrace

None

I am attaching logs from all the nodes. The timestamp this leader election occurred is at `2021/12/13 23:45:34`

**Comment by vdamle** [comment]
[node-1-geth.txt.gz](https://github.com/ConsenSys/quorum/files/7723160/node-1-geth.txt.gz)
[node-2-geth.log.gz](https://github.com/ConsenSys/quorum/files/7723161/node-2-geth.log.gz)
[node-3-geth.log.gz](https://github.com/ConsenSys/quorum/files/7723164/node-3-geth.log.gz)
[node-4-geth.log.gz](https://github.com/ConsenSys/quorum/files/7723166/node-4-geth.log.gz)
[node-5-geth.log.gz](https://github.com/ConsenSys/quorum/files/7723168/node-5-geth.log.gz)
[node-6-geth.log.gz](https://github.com/ConsenSys/quorum/files/7723170/node-6-geth.log.gz)
[node-8-geth.log.gz](https://github.com/ConsenSys/quorum/files/7723172/node-8-geth.log.gz)

**Comment by antonydenyer** [comment]
This looks like a problem that is inherent with raft. There's the possibility of having a split brain scenario, especially under load where it's not clear who the leader is. I recommend you look at using QBFT instead.

Was there a particular reason you're using raft?

**Comment by antonydenyer** [comment]
Closing as stale, feel free to re-open.
