### ISSUE TITLE
Some transaction results are lost after upgrading to Quorum@v21.1.10

### ISSUE THREAD

**Issue by sokiaoba** [ConsenSys/quorum#1285]
#### System information

Quorum Version: v21.1.0 -> v21.10.0

#### Expected behaviour

All existing transaction results successfully migrate to Quorum@v21.10.0.

#### Actual behaviour

Some transaction results are lost sometimes (not always) after upgrading to Quorum@v21.10.0.

#### Steps to reproduce the behaviour

1. create a Quorum@v21.1.0 network (with 1 transaction node, 4 validator nodes, IBFT)
2. create an ERC20 contract (not exactly ERC20 contract, but pretty similar one) on the network
3. send a transaction using the contract, so an specific address can have a token balance
4. upgrade the network to Quorum@v21.10.0
5. block generation restarts
6. the result of `3` is not reflected 

By `not reclected`, specifically I mean

* the transaction itself exists in the network
* the transaction is included in a different block from the one which originally included it before the upgrade (this behaviour by itself looks reorganization)
* the result of the transaction (specifically information below) is lost
    * transaction receipt
    * token balance of the address

#### Backtrace

* information of the transaction (before/after upgrade)
    * [tx_info_v21.1.0 (before upgrade).log](https://github.com/ConsenSys/quorum/files/7762378/tx_info_v21.1.0.before.upgrade.log)
    * [tx_info_v21.10.0 (after update).log](https://github.com/ConsenSys/quorum/files/7762402/tx_info_v21.10.0.after.update.log)

* node logs in upgrading to Quorum@v21.10.0
    * [txnode.log](https://github.com/ConsenSys/quorum/files/7762366/txnode.log)
    * [validator-1.log](https://github.com/ConsenSys/quorum/files/7762367/validator-1.log)
    * [validator-2.log](https://github.com/ConsenSys/quorum/files/7762368/validator-2.log)
    * [validator-3.log](https://github.com/ConsenSys/quorum/files/7762369/validator-3.log)
    * [validator-4.log](https://github.com/ConsenSys/quorum/files/7762370/validator-4.log)

Thank you.

**Comment by baptiste-b-pegasys** [comment]
Hello, from your logs, I see you are using a hostname for each node, but it can't resolve the IP with the DNS.

Are you able to `ping quorum-node-prod-validator-4-0.quorum-node-prod-validator-4.prod.svc.cluster.local` or `dig quorum-node-prod-validator-4-0.quorum-node-prod-validator-4.prod.svc.cluster.local`?

Or can you try with an IP directly in order to resolve this issue?

**Comment by sokiaoba** [comment]
@baptiste-b-pegasys 

Thank you for your reply.

> Are you able to ping quorum-node-prod-validator-4-0.quorum-node-prod-validator-4.prod.svc.cluster.local or dig quorum-node-prod-validator-4-0.quorum-node-prod-validator-4.prod.svc.cluster.local?

Yes, ping works from each node to each node.

Below is an example.

```
% kubectl iexec tx
/ # hostname
quorum-node-prod-tx-1-0
/ # ping quorum-node-prod-validator-4-0.quorum-node-prod-validator-4.prod.svc.cluster.local
PING quorum-node-prod-validator-4-0.quorum-node-prod-validator-4.prod.svc.cluster.local (10.0.0.16): 56 data bytes
64 bytes from 10.0.0.16: seq=0 ttl=63 time=0.078 ms
64 bytes from 10.0.0.16: seq=1 ttl=63 time=0.113 ms
64 bytes from 10.0.0.16: seq=2 ttl=63 time=0.068 ms
64 bytes from 10.0.0.16: seq=3 ttl=63 time=0.071 ms
64 bytes from 10.0.0.16: seq=4 ttl=63 time=0.073 ms
64 bytes from 10.0.0.16: seq=5 ttl=63 time=0.102 ms
```

I was also wondering why I get errors like below.

```
quorum-node-prod-tx-1-0 quorum-node-prod-tx-1-quorum ERROR[12-22|01:48:44.675] Node URL enode://242088e99d21fb41cde665c7336b8d2f3cc0b7715306071d54955d5b168b4da5ae37652eecfde0addd1178a8da6359083f93dc43aaec685111ee8ef5a24f818c@quorum-node-prod-validator-1-0.quorum-node-prod-validator-1.prod.svc.cluster.local:30303?discport=0: lookup quorum-node-prod-validator-1-0.quorum-node-prod-validator-1.prod.svc.cluster.local: no such host
```

It seems after a few minutes after getting those errors, the nodes start to communicate each other and block generation & tx propagation start to work somehow.

**Comment by baptiste-b-pegasys** [comment]
Ah I think it is a known issue in GoLang with the DNS in K8S

https://medium.com/box-tech-blog/a-trip-down-the-dns-rabbit-hole-understanding-the-role-of-kubernetes-golang-libc-systemd-41fd80ffd679

But before trying another version of the geth binary, can you add these lines in the deployment file of kubernetes:
```
...
    spec:
      serviceAccountName: xxx
      dnsConfig:
        options:
          - name: use-vc
          - name: ndots
            value: "2"
...
```
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config

The idea is to change the resolv.conf of the pods.

**Comment by sokiaoba** [comment]
Sorry for late reply. Thanks, I'll try the dns settings tomorrow, but do you think the temporary network error could be the cause of data loss? @baptiste-b-pegasys

**Comment by baptiste-b-pegasys** [comment]
Hello, can I have the procedure to have the logs in the 21.1.0. I created a contract that emit an event, and getting the tx receipt, in the 21.1.0 version, but the logs are empty.

**Comment by antonydenyer** [comment]
@sokiaoba I just wanted to double-check how you are performing the network upgrade are you walking through the versions ie `v21.1.0` -> `v21.4.0` etc or are you jumping from `v21.1.0` to `v21.10`?

Also just wanted to confirm that I couldn't reproduce the issue using https://github.com/ConsenSys/quorum-dev-quickstart. The events are retained across versions.

**Comment by antonydenyer** [comment]
The other question I have is that in the logs the `blockHash` changes from the before upgrade to the after upgrade. Why is that, the data should be the same.

**Comment by sokiaoba** [comment]
@baptiste-b-pegasys 

> Hello, can I have the procedure to have the logs in the 21.1.0. I created a contract that emit an event, and getting the tx receipt, in the 21.1.0 version, but the logs are empty.

Thank you.

I tried the setings but still got the same network error.
https://github.com/ConsenSys/quorum/issues/1285#issuecomment-1002582508

The cause of it might be because simply a node can't reach other nodes while other nodes are restarting. 
I realized the following pattern.

* Restart all nodes at a time -> get the error
* Restart one single node -> no error

> Hello, can I have the procedure to have the logs in the 21.1.0. I created a contract that emit an event, and getting the tx receipt, in the 21.1.0 version, but the logs are empty.

The helm chart I'm using for Quorum is a tweaked version of https://github.com/ConsenSys/quorum-azure. 
Despite I tweaked the chart, the network settings are basically as same as the original. 
(I changed the chart, because I needed to have dev & prod environment in a single k8s cluster, and to deploy Quorum network using Argocd)

And the contract is also a tweaked version (almost identical though) of https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol.

**Comment by sokiaoba** [comment]
@antonydenyer 

Thank you.

> I just wanted to double-check how you are performing the network upgrade are you walking through the versions ie v21.1.0 -> v21.4.0 etc or are you jumping from v21.1.0 to v21.10?

Yes, I tried to jump from v21.1.0 to v21.10.

> Also just wanted to confirm that I couldn't reproduce the issue using https://github.com/ConsenSys/quorum-dev-quickstart. The events are retained across versions.

When it comes to the chart I used, please check https://github.com/ConsenSys/quorum/issues/1285#issuecomment-1010867144.

> The other question I have is that in the logs the blockHash changes from the before upgrade to the after upgrade. Why is that, the data should be the same.

That's the issue I wondered too. I guessed reoganization might have occured during the process of upgrade, because, after the upgrade, a specific transaction was included in another block.

**Comment by antonydenyer** [comment]
For the `blockHash` to change the reorg would have to happen all the way back to before that transaction. In the logs you can see this happening but the question is why the node thinks it needs to reorg. 

I think you have your answer
> Restart one single node -> no error

But if you want to investigate further it would be helpful, the main question is why the reorg and which node is advertising it?

**Comment by sokiaoba** [comment]
Thanks. I'll lower the priority of upgrade for now. I'll report if I run into the same issue.
