### ISSUE TITLE
GoQuorum Geth Crash with fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by frankie-lim-partior** [ConsenSys/quorum#1287]
#### System information

Geth version: `geth version`
Geth
Version: 1.9.25-stable
Git Commit: 919800f019cc5d2b931b5cd81600640a8e7cd444
Quorum Version: 21.10.0
Architecture: amd64
Protocol Versions: [65 64 63]
Network Id: 1337
Go Version: go1.15.6
Operating System: linux
GOPATH=
GOROOT=go

OS & Version: Windows/Linux/OSX
Running on Google CLoud Platform GKE Kubernetes
/ # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.14.2
PRETTY_NAME="Alpine Linux v3.14"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

#### Expected behaviour
When transactions are send to the Geth RPC, it continue to process the txn and return receipt without crashing.

#### Actual behaviour
Geth (GoQuorum) crash with "fatal error: concurrent map iteration and map write" randomly, especially when we are sending > ~10 send transaction call per seconds to Geth.

#### Steps to reproduce the behaviour
Keep sending private smart contract transaction to Geth, at more than ~10 Txn per seconds, it would randomly crash. With public smart contract transaction, it does not crash even with 100 TPS.

#### Backtrace
Full log attached

````
fatal error: concurrent map iteration and map write

goroutine 82381 [running]:
runtime.throw(0x17480af, 0x26)
	runtime/panic.go:1116 +0x72 fp=0xc00db61980 sp=0xc00db61950 pc=0x450c52
runtime.mapiternext(0xc00db61aa8)
	runtime/map.go:853 +0x554 fp=0xc00db61a00 sp=0xc00db61980 pc=0x429f14
github.com/ethereum/go-ethereum/core/state.Storage.Copy(0xc00b8561e0, 0xc00bc9cc00)
	github.com/ethereum/go-ethereum/core/state/state_object.go:54 +0x156 fp=0xc00db61b18 sp=0xc00db61a00 pc=0x9541b6
github.com/ethereum/go-ethereum/core/state.(*stateObject).deepCopy(0xc00da03400, 0xc00db86000, 0xc00db61c98)
	github.com/ethereum/go-ethereum/core/state/state_object.go:439 +0x196 fp=0xc00db61c00 sp=0xc00db61b18 pc=0x956f96
github.com/ethereum/go-ethereum/core/state.(*StateDB).Copy(0xc00dad2000, 0xc00db29e00)
	github.com/ethereum/go-ethereum/core/state/statedb.go:794 +0x752 fp=0xc00db61f28 sp=0xc00db61c00 pc=0x95e8b2
github.com/ethereum/go-ethereum/miner.(*worker).pending(0xc0008f78c0, 0x1711dad, 0x7, 0x0, 0x0, 0x0)
	github.com/ethereum/go-ethereum/miner/worker.go:294 +0x290 fp=0xc00db61ff0 sp=0xc00db61f28 pc=0xe9da70
github.com/ethereum/go-ethereum/miner.(*Miner).Pending(...)
	github.com/ethereum/go-ethereum/miner/miner.go:187
github.com/ethereum/go-ethereum/eth.(*EthAPIBackend).StateAndHeaderByNumber(0xc000ae8f60, 0x19bd080, 0xc00917c270, 0xfffffffffffffffe, 0xc00d7f7960, 0x0, 0x0, 0x3c, 0x21e9fae)
	github.com/ethereum/go-ethereum/eth/api_backend.go:174 +0x2a5 fp=0xc00db620e8 sp=0xc00db61ff0 pc=0xf00125
github.com/ethereum/go-ethereum/eth.(*EthAPIBackend).StateAndHeaderByNumberOrHash(0xc000ae8f60, 0x19bd080, 0xc00917c270, 0xc00f8c9188, 0x0, 0x0, 0x0, 0xc00db4fb00, 0xc00dba2a80, 0x181fe70, ...)
	github.com/ethereum/go-ethereum/eth/api_backend.go:192 +0x578 fp=0xc00db62260 sp=0xc00db620e8 pc=0xf00998
github.com/ethereum/go-ethereum/internal/ethapi.DoCall(0x19bd080, 0xc00917c270, 0x19dc320, 0xc000ae8f60, 0xc00b9df868, 0xc00f759240, 0xc00f8c99f8, 0xc00b205a20, 0xc00db00580, 0xc00b205a00, ...)
	github.com/ethereum/go-ethereum/internal/ethapi/api.go:944 +0x106 fp=0xc00db62648 sp=0xc00db62260 pc=0xdb73a6
github.com/ethereum/go-ethereum/internal/ethapi.DoEstimateGas.func1(0x1cc352, 0x19bd000, 0xc00bc9c4e0, 0x0, 0x0)
	github.com/ethereum/go-ethereum/internal/ethapi/api.go:1137 +0x193 fp=0xc00db62fc8 sp=0xc00db62648 pc=0xdcf4b3
github.com/ethereum/go-ethereum/internal/ethapi.DoEstimateGas(0x19bd080, 0xc00917c270, 0x19dc320, 0xc000ae8f60, 0xc00b9df868, 0xc00f759240, 0xc00f8c99f8, 0xc00b205a20, 0xc00db00580, 0xc00b205a00, ...)
	github.com/ethereum/go-ethereum/internal/ethapi/api.go:1149 +0x1fa fp=0xc00db63268 sp=0xc00db62fc8 pc=0xdb8ada
github.com/ethereum/go-ethereum/internal/ethapi.(*SendTxArgs).setDefaults(0xc00b9df810, 0x19bd080, 0xc00917c270, 0x19dc320, 0xc000ae8f60, 0x0, 0x0)
	github.com/ethereum/go-ethereum/internal/ethapi/api.go:1894 +0x299 fp=0xc00db63380 sp=0xc00db63268 pc=0xdbfcb9
github.com/ethereum/go-ethereum/internal/ethapi.(*PublicTransactionPoolAPI).SendTransaction(0xc00113fce0, 0x19bd080, 0xc00917c270, 0x0, 0x0, 0xc00e963040, 0x4, 0x4, 0x0, 0x0, ...)
	github.com/ethereum/go-ethereum/internal/ethapi/api.go:2075 +0x1d7 fp=0xc00db63828 sp=0xc00db63380 pc=0xdc2ed7
runtime.call256(0xc006367dd0, 0xc0009fccb8, 0xc00bca4690, 0xc0000000f0)
	runtime/asm_amd64.s:543 +0x5c fp=0xc00db63938 sp=0xc00db63828 pc=0x48821c
reflect.Value.call(0xc020b52c00, 0xc0009fccb8, 0x13, 0x170d454, 0x4, 0xc00bbfbe00, 0x3, 0x3, 0xc00bbfbe30, 0xc00b2059c0, ...)
	reflect/value.go:476 +0x8c7 fp=0xc00db63b50 sp=0xc00db63938 pc=0x4bcc87
reflect.Value.Call(0xc020b52c00, 0xc0009fccb8, 0x13, 0xc00bbfbe00, 0x3, 0x3, 0x16, 0x7fa8ce35ee58, 0x30)
	reflect/value.go:337 +0xb9 fp=0xc00db63bd0 sp=0xc00db63b50 pc=0x4bc179
github.com/ethereum/go-ethereum/rpc.(*callback).call(0xc002091020, 0x19bd080, 0xc00917c270, 0xc00f363c20, 0x13, 0xc00b2059c0, 0x1, 0x1, 0x0, 0x0, ...)
	github.com/ethereum/go-ethereum/rpc/service.go:206 +0x2c5 fp=0xc00db63cd8 sp=0xc00db63bd0 pc=0xbbcfc5
github.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc00eb08fc0, 0x19bd080, 0xc00917c210, 0xc00ed83810, 0xc002091020, 0xc00b2059c0, 0x1, 0x1, 0x1)
	github.com/ethereum/go-ethereum/rpc/handler.go:416 +0xd9 fp=0xc00db63d48 sp=0xc00db63cd8 pc=0xbb45b9
github.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc00eb08fc0, 0xc0055b81e0, 0xc00ed83810, 0x203001)
	github.com/ethereum/go-ethereum/rpc/handler.go:360 +0x345 fp=0xc00db63e30 sp=0xc00db63d48 pc=0xbb34a5
github.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc00eb08fc0, 0xc0055b81e0, 0xc00ed83810, 0x19a6001)
	github.com/ethereum/go-ethereum/rpc/handler.go:298 +0x1be fp=0xc00db63ef8 sp=0xc00db63e30 pc=0xbb29fe
github.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1(0xc0055b81e0)
	github.com/ethereum/go-ethereum/rpc/handler.go:139 +0x46 fp=0xc00db63f68 sp=0xc00db63ef8 pc=0xbc2666
github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1(0xc00eb08fc0, 0xc00e595e00)
	github.com/ethereum/go-ethereum/rpc/handler.go:226 +0xd2 fp=0xc00db63fd0 sp=0xc00db63f68 pc=0xbc2832
runtime.goexit()
	runtime/asm_amd64.s:1374 +0x1 fp=0xc00db63fd8 sp=0xc00db63fd0 pc=0x489a21
created by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc
	github.com/ethereum/go-ethereum/rpc/handler.go:222 +0x66

goroutine 1 [chan receive, 9 minutes]:
github.com/ethereum/go-ethereum/node.(*Node).Wait(...)
	github.com/ethereum/go-ethereum/node/node.go:445
main.geth(0xc00012a580, 0x0, 0x0)
	github.com/ethereum/go-ethereum/cmd/geth/main.go:399 +0x157
gopkg.in/urfave/cli%2ev1.HandleAction(0x149dc00, 0x18226e0, 0xc00012a580, 0xc0004bc060, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x82
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0000a0000, 0xc00003c500, 0x49, 0x50, 0x0, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5f5
main.main()
	github.com/ethereum/go-ethereum/cmd/geth/main.go:312 +0x55
````
[crash.log.zip](https://github.com/ConsenSys/quorum/files/7792088/crash.log.zip)

**Comment by SatpalSandhu61** [comment]
You are using a pretty old version of GoQuorum - I believe this issue is fixed in [PR # 684](https://github.com/ConsenSys/quorum/pull/684), which was releasing in V2.2.4.

If you upgrade to a more recent release then this issue should not occur.
Closing this issue. Please re-open if a version upgrade doesn't fix the problem.

**Comment by frankie-lim-partior** [comment]
@SatpalSandhu61 We are using the latest quorum v21.10.0. Could you please re-open this issue and help check if the previous bug got re-introduced?. thanks!

**Comment by baptiste-b-pegasys** [comment]
Thank you for raising this issue. At first sight, this code originate from original go-ethereum source code.

I investigate more to see if its usage in go-quorum defers from geth itself.
Are you able to reproduce this with go-ethereum? as it is public tx, it will be nice to see if it is reproducable with geth too.

**Comment by frankie-lim-partior** [comment]
Thanks. We can easily reproduce with private transactions on GoQuorum. Once we switch to sending public transaction, we are not able to reproduce it.

**Comment by baptiste-b-pegasys** [comment]
OK thank you for the precision, I misunderstood then.

**Comment by baptiste-b-pegasys** [comment]
Can you give me the example of contract, transactions you are making. (or a simplified one)
I've done our profiling test, yet I can't reproduce that.
Also I see you are using GKE, what deployment script are you using?
Many thanks.

**Comment by frankie-lim-partior** [comment]
[simple.sol.zip](https://github.com/ConsenSys/quorum/files/7796617/simple.sol.zip)
We can reproduce with simply using the simple contract example attached. The trick is to make it a private contract, then repeatly send transaction that call the transfer function at >~10 TPS. If I hit it will just 1 to 5 TPS, it does not crash. If we make it a public contract, we can hit it at many tens of TPS without crashing.

For the GKE K8s deployment, we created out own helm chart based on Qubernetes. 

Thanks. Happy new year!

**Comment by frankie-lim-partior** [comment]
@baptiste-b-pegasys We are using Hyperledger Caliper (Quorum modified SUT) to inject the attached smart contract and transactions and specified TPS rate to the chain. May I know the tool you use for your profiling test for transactions injection? Can the tool / script be shared with us so that we can use it to reproduce from our end? 

Thanks! Happy new year!

**Comment by baptiste-b-pegasys** [comment]
Hi Happy New Year,

We have a jmeter profiling tool, I adapted it to the simple contract.
https://github.com/ConsenSys/quorum-profiling

Here is a minimal zip: [quorum-profiling.zip](https://github.com/ConsenSys/quorum/files/7807602/quorum-profiling.zip)
Need to change url, port, addresses and pub keys, it uses a docker image of jmeter we have.

I am doing this now over a k3s deployment made from qubernetes template.

I want to use Caliper.
```
user@ubuntu:~/caliper-benchmarks$ docker run \
    -v $PWD:/hyperledger/caliper/workspace \
    -e CALIPER_BIND_SUT=fabric:1.4.0 \
    -e CALIPER_BENCHCONFIG=benchmarks/scenario/simple/config.yaml \
    -e CALIPER_NETWORKCONFIG=networks/fabric/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml \
    --name caliper hyperledger/caliper:0.4.0 launch manager
```
for SUT, what should I use? Do you have a page to follow?

Thanks.

**Comment by frankie-lim-partior** [comment]
@baptiste-b-pegasys I am using the Caliper forked by Marco https://github.com/MarcoMazzoni/caliper which support Quorum SUT (https://github.com/MarcoMazzoni/caliper/tree/master/packages/caliper-quorum).

Then I customised my benchmark profile based on https://github.com/MarcoMazzoni/quorum-caliper-benchmarks/tree/master/ibft/5n-ibft-mqtt-priv

**Comment by baptiste-b-pegasys** [comment]
Ok Thank you, I have trouble to install it with npm (source install) and there is no quick start with benchmark and net config files.

**Comment by frankie-lim-partior** [comment]
@baptiste-b-pegasys from the crash dump, are you able to identify the potential reason why the GoQuourum geth crashing?  Any thing we can try from our end (config change, IaC change, K8s change, contract change etc) to help narrow down the root cause? Or any further logs we can help captured to assist with the debug?

**Comment by baptiste-b-pegasys** [comment]
no, and I am seeking to reproduce this issue in order to test a fix (a mutex lock added)

**Comment by frankie-lim-partior** [comment]
@baptiste-b-pegasys if you have a test docker image with the mutex lock fix, I dont mind testing it in my setup :-)

**Comment by baptiste-b-pegasys** [comment]
Can you try this `docker pull ghcr.io/baptiste-b-pegasys/quorum:fix21.10`

**Comment by frankie-lim-partior** [comment]
@baptiste-b-pegasys I am testing the fix. thanks!

**Comment by frankie-lim-partior** [comment]
@baptiste-b-pegasys good news and bad news. I have use the above docker image with the fix, and rerun the test with Caliper.

1. Good news is, we are no longer able to reproduce the error "fatal error: concurrent map iteration and map write" when sending high rate transaction. I think you are on the right track!
2. We are able to send over 100TPS send rate to GoQuorum without it crashing using the test image. With the official 21.10.0 images, almost all GoQourum instances will crash everytime with the fatal error whenever such high send rate it executed.
3. Bad news is, randomly at a low occurrence rate (~ 1 in 10 test execution), the GoQuorum crash with Panic error below. We are able to reproduce it multiple times. Attached are 3 instance of the logs.
```
Panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xbc64c5]
oroutine 1 [running]:
github.com/ethereum/go-ethereum/core/mps.(*DefaultPrivateStateRepository).DefaultState(0x0, 0x896f85bb415b98d4, 0xdfb5f92c97a8cc07, 0x61c94a63b77472e1)
	github.com/ethereum/go-ethereum/core/mps/default_psr.go:44 +0x5
github.com/ethereum/go-ethereum/core.(*BlockChain).loadLastState(0xc000137900, 0x16ddf00, 0x0)
	github.com/ethereum/go-ethereum/core/blockchain.go:515 +0x1be
github.com/ethereum/go-ethereum/core.NewBlockChain(0x19d66a0, 0xc0001215e0, 0xc00069cf00, 0xc0000a8800, 0x19d4b20, 0xc000282140, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/ethereum/go-ethereum/core/blockchain.go:313 +0x9ab
github.com/ethereum/go-ethereum/eth.New(0xc000115380, 0xc0005f8a00, 0x3, 0x0, 0x0)
	github.com/ethereum/go-ethereum/eth/backend.go:228 +0xd39
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService(0xc000115380, 0xc0005f8a00, 0x0, 0x3e8, 0x0)
	github.com/ethereum/go-ethereum/cmd/utils/flags.go:2017 +0xf1
main.makeFullNode(0xc0000a58c0, 0x2549, 0x7, 0xc000625f00)
	github.com/ethereum/go-ethereum/cmd/geth/config.go:180 +0x12f
main.geth(0xc0000a58c0, 0x0, 0x0)
	github.com/ethereum/go-ethereum/cmd/geth/main.go:394 +0xf4
gopkg.in/urfave/cli%2ev1.HandleAction(0x149ec00, 0x1823838, 0xc0000a58c0, 0xc000659da0, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x82
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc000117380, 0xc000130000, 0x49, 0x50, 0x0, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5f5
main.main()
	github.com/ethereum/go-ethereum/cmd/geth/main.go:312 +0x55

``` 
4. Once the GoQuorum instance crash with the panic above, even after I restart the process, it will continue to crash with the same panic, until I wipe out the persistence storage and restart. Looks like some data has been corrupted in the persistent storage when it crash . We can consistently reproduce this.

Please analyse and let us know what else we can try for you to narrow down the bug. 

Thanks. Have a nice weekend!

[Segmentation_Violation.zip](https://github.com/ConsenSys/quorum/files/7827519/Segmentation_Violation.zip)

**Comment by baptiste-b-pegasys** [comment]
Thank you very much for your return.

It's not clear to me how it's possible, but I am adding a security check for that seg fault.

Instead of having a seg fault, you should have a warning : `DefaultPrivateStateRepository is nil when calling DefaultState`.
This new images is: `ghcr.io/baptiste-b-pegasys/quorum:fix21.10-2`

Moreover, an alternative version will cause a reset of the storage when it happens: `ghcr.io/baptiste-b-pegasys/quorum:fix21.10-3`.

It would be nice to have your test environment in order to reproduce the case.
Thx

**Comment by frankie-lim-partior** [comment]
@baptiste-b-pegasys  thanks! will test the two images and revert.

**Comment by frankie-lim-partior** [comment]
@baptiste-b-pegasys I have tested the two new images:
1. quorum:fix21.10-2 - I am only able to reproduce once. Attached is the log. I can see the warning : " DefaultPrivateStateRepository is nil when calling DefaultState", after which looks like it tries to recover block missing state, and after awhile crash with below. After pod restart, geth working fine. I am not able to reproduce it subsequently. Please analyze if you can find anything in the log.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc86046]

goroutine 1 [running]:
[fix2-q-9-crash.log.zip](https://github.com/ConsenSys/quorum/files/7845787/fix2-q-9-crash.log.zip)

github.com/ethereum/go-ethereum/core.(*BlockChain).SubscribeChainHeadEvent(0x0, 0xc004a780c0, 0xc004a780c0, 0x19)
	github.com/ethereum/go-ethereum/core/blockchain.go:2838 +0x26
github.com/ethereum/go-ethereum/core.(*ChainIndexer).Start(0xc0000a84b0, 0x19a80c0, 0x0)
	github.com/ethereum/go-ethereum/core/chain_indexer.go:150 +0x5d
github.com/ethereum/go-ethereum/eth.New(0xc00009ad00, 0xc00062f500, 0x3, 0x0, 0x0)
	github.com/ethereum/go-ethereum/eth/backend.go:239 +0xdbb
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService(0xc00009ad00, 0xc00062f500, 0x0, 0x3e8, 0x0)
	github.com/ethereum/go-ethereum/cmd/utils/flags.go:2017 +0xf1
main.makeFullNode(0xc00009eb00, 0x2549, 0x7, 0xc00062c160)
	github.com/ethereum/go-ethereum/cmd/geth/config.go:180 +0x12f
main.geth(0xc00009eb00, 0x0, 0x0)
	github.com/ethereum/go-ethereum/cmd/geth/main.go:394 +0xf4
gopkg.in/urfave/cli%2ev1.HandleAction(0x149ec20, 0x1823890, 0xc00009eb00, 0xc000603e00, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x82
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0005b8680, 0xc000132000, 0x49, 0x50, 0x0, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5f5
main.main()
	github.com/ethereum/go-ethereum/cmd/geth/main.go:312 +0x55
```

2. quorum:fix21.10-3 - I am not able to reproduce the original fatal error or the panic!

I will continue to try to reproduce. The fixes looks very promising. Will these be included in the next release?

Thanks alot

**Comment by baptiste-b-pegasys** [comment]
Thank you for your return.

2nd Version (*-3) is better, if I understand well.

Yes I think they will be introduced quickly.

**Comment by frankie-lim-partior** [comment]
Yes, quorum:fix21.10-3 is better!  thanks alot

**Comment by frankie-lim-partior** [comment]
@baptiste-b-pegasys new findings. with quorum:fix21.10-3, I cant reproduce the original fatal error and the process didnt panic while under high load. 

However, I notice that once I stop the quorum container, keep the persistent storage, then redeploy the quorum container to use the existing persistent storage (with LevelDB intact), all my instances will panic and keep restarting. 3 full logs attached.

```
INFO [01-13|01:18:12.546] Allocated trie memory caches             clean=663.00MiB dirty=663.00MiB
INFO [01-13|01:18:12.546] Allocated cache and file handles         database=/etc/quorum/qdata/dd/geth/chaindata cache=1.94GiB handles=524288
DEBUG[01-13|01:18:12.732] Chain freezer table opened               database=/etc/quorum/qdata/dd/geth/chaindata/ancient table=headers items=0 size=0.00B
DEBUG[01-13|01:18:12.732] Chain freezer table opened               database=/etc/quorum/qdata/dd/geth/chaindata/ancient table=hashes  items=0 size=0.00B
DEBUG[01-13|01:18:12.733] Chain freezer table opened               database=/etc/quorum/qdata/dd/geth/chaindata/ancient table=bodies  items=0 size=0.00B
DEBUG[01-13|01:18:12.733] Chain freezer table opened               database=/etc/quorum/qdata/dd/geth/chaindata/ancient table=receipts items=0 size=0.00B
DEBUG[01-13|01:18:12.734] Chain freezer table opened               database=/etc/quorum/qdata/dd/geth/chaindata/ancient table=diffs    items=0 size=0.00B
INFO [01-13|01:18:12.734] Opened ancient database                  database=/etc/quorum/qdata/dd/geth/chaindata/ancient
DEBUG[01-13|01:18:12.734] Current full block not old enough        number=1824 hash="9c97eb…093f33" delay=3162240
DEBUG[01-13|01:18:12.735] Account Extra Data root                  hash="000000…000000"
INFO [01-13|01:18:12.735] Initialised chain configuration          config="{ChainID: 1000 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 IsQuorum: true Constantinople: 0 TransactionSizeLimit: 64 MaxCodeSize: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: <nil> YOLO v2: <nil> PrivacyEnhancements: <nil> PrivacyPrecompile: <nil> Engine: istanbul}"
INFO [01-13|01:18:12.736] Initialising Ethereum protocol           name=eth     versions="[65 64 63]" network=1000 dbversion=8
INFO [01-13|01:18:12.736] Initialising Quorum consensus protocol   name=istanbul versions="[100 99 64]" network=1000 dbversion=8
WARN [01-13|01:18:12.738] DefaultPrivateStateRepository is nil when calling DefaultState 
WARN [01-13|01:18:12.738] Head private state missing, resetting chain number=1824 hash="9c97eb…093f33"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc6ecd4]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).NumberU64(...)
	github.com/ethereum/go-ethereum/core/types/block.go:348
github.com/ethereum/go-ethereum/core.(*BlockChain).SetHeadBeyondRoot(0xc000139900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/ethereum/go-ethereum/core/blockchain.go:687 +0x1f4
github.com/ethereum/go-ethereum/core.(*BlockChain).SetHead(0xc000139900, 0x0, 0xc00018c380, 0x0)
	github.com/ethereum/go-ethereum/core/blockchain.go:566 +0x45
github.com/ethereum/go-ethereum/core.(*BlockChain).ResetWithGenesisBlock(0xc000139900, 0xc0000fe090, 0x0, 0x0)
	github.com/ethereum/go-ethereum/core/blockchain.go:838 +0x65
github.com/ethereum/go-ethereum/core.(*BlockChain).Reset(0xc000139900, 0x1752c84, 0x2b)
	github.com/ethereum/go-ethereum/core/blockchain.go:831 +0x37
github.com/ethereum/go-ethereum/core.(*BlockChain).loadLastState(0xc000139900, 0x16de000, 0x0)
	github.com/ethereum/go-ethereum/core/blockchain.go:518 +0x14ff
github.com/ethereum/go-ethereum/core.NewBlockChain(0x19d6720, 0xc00000e2a0, 0xc0006a86c0, 0xc00013e900, 0x19d4ba0, 0xc0000da640, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/ethereum/go-ethereum/core/blockchain.go:313 +0x9ab
github.com/ethereum/go-ethereum/eth.New(0xc00028b790, 0xc00011dc00, 0x3, 0x0, 0x0)
	github.com/ethereum/go-ethereum/eth/backend.go:228 +0xd39
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService(0xc00028b790, 0xc00011dc00, 0x0, 0x3e8, 0x0)
	github.com/ethereum/go-ethereum/cmd/utils/flags.go:2017 +0xf1
main.makeFullNode(0xc0000a7e40, 0x2549, 0x7, 0xc0006c6060)
	github.com/ethereum/go-ethereum/cmd/geth/config.go:180 +0x12f
main.geth(0xc0000a7e40, 0x0, 0x0)
	github.com/ethereum/go-ethereum/cmd/geth/main.go:394 +0xf4
gopkg.in/urfave/cli%2ev1.HandleAction(0x149ec20, 0x1823898, 0xc0000a7e40, 0xc0006a87e0, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x82
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00040d520, 0xc000132000, 0x4e, 0x50, 0x0, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5f5
main.main()
	github.com/ethereum/go-ethereum/cmd/geth/main.go:312 +0x55
```

To recover, I would need to clear the persistent storage and start from scratch. I dont see this behaviour in the official release image. Please investigate. Let me know if any thing I can test.

[fix-3-crash-on-restart.zip](https://github.com/ConsenSys/quorum/files/7859054/fix-3-crash-on-restart.zip)

**Comment by frankie-lim-partior** [comment]
@baptiste-b-pegasys  more update as I continue to perform more stress test against  **quorum:fix21.10-3** . 

1. I Cannot reproduce original  "fatal error: concurrent map iteration" issue. 
2. While it is very much lower rate of occurrence, I am able to reproduce the "panic: runtime error: invalid memory address or nil pointer dereference" issue twice today. After which the geth cannot recover, keep crashing after restart until I clear the persistent volume and start from scratch. Attached is the log.

```
INFO [01-13|10:08:51.915] Initialising Ethereum protocol           name=eth     versions="[65 64 63]" network=1000 dbversion=8
INFO [01-13|10:08:51.915] Initialising Quorum consensus protocol   name=istanbul versions="[100 99 64]" network=1000 dbversion=8
WARN [01-13|10:08:51.918] DefaultPrivateStateRepository is nil when calling DefaultState 
WARN [01-13|10:08:51.918] Head private state missing, resetting chain number=30216 hash="caaab9…a70075"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc6ecd4]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).NumberU64(...)
	github.com/ethereum/go-ethereum/core/types/block.go:348
github.com/ethereum/go-ethereum/core.(*BlockChain).SetHeadBeyondRoot(0xc000139900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/ethereum/go-ethereum/core/blockchain.go:687 +0x1f4
github.com/ethereum/go-ethereum/core.(*BlockChain).SetHead(0xc000139900, 0x0, 0xc0000e8d20, 0x0)
	github.com/ethereum/go-ethereum/core/blockchain.go:566 +0x45
github.com/ethereum/go-ethereum/core.(*BlockChain).ResetWithGenesisBlock(0xc000139900, 0xc0000de750, 0x0, 0x0)
	github.com/ethereum/go-ethereum/core/blockchain.go:838 +0x65
github.com/ethereum/go-ethereum/core.(*BlockChain).Reset(0xc000139900, 0x1752c84, 0x2b)
	github.com/ethereum/go-ethereum/core/blockchain.go:831 +0x37
github.com/ethereum/go-ethereum/core.(*BlockChain).loadLastState(0xc000139900, 0x16de000, 0x0)
	github.com/ethereum/go-ethereum/core/blockchain.go:518 +0x14ff
github.com/ethereum/go-ethereum/core.NewBlockChain(0x19d6720, 0xc00042e520, 0xc0004ff260, 0xc00013ef00, 0x19d4ba0, 0xc00014c500, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/ethereum/go-ethereum/core/blockchain.go:313 +0x9ab
github.com/ethereum/go-ethereum/eth.New(0xc0003ef1e0, 0xc000348a00, 0x3, 0x0, 0x0)
	github.com/ethereum/go-ethereum/eth/backend.go:228 +0xd39
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService(0xc0003ef1e0, 0xc000348a00, 0x0, 0x3e8, 0x0)
	github.com/ethereum/go-ethereum/cmd/utils/flags.go:2017 +0xf1
main.makeFullNode(0xc0005a6840, 0x2549, 0x7, 0xc0006719a0)
	github.com/ethereum/go-ethereum/cmd/geth/config.go:180 +0x12f
main.geth(0xc0005a6840, 0x0, 0x0)
	github.com/ethereum/go-ethereum/cmd/geth/main.go:394 +0xf4
gopkg.in/urfave/cli%2ev1.HandleAction(0x149ec20, 0x1823898, 0xc0005a6840, 0xc00065d140, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x82
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0003d5ba0, 0xc000132000, 0x4e, 0x50, 0x0, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5f5
main.main()

	github.com/ethereum/go-ethereum/cmd/geth/main.go:312 +0x55

```

Hopefully you can identify the issue from the log. Thanks

[crash1.log.zip](https://github.com/ConsenSys/quorum/files/7861947/crash1.log.zip)

**Comment by frankie-lim-partior** [comment]
@baptiste-b-pegasys Additional info, I have repeatedly stress test with PUBLIC smart contract against quorum:fix21.10-3 
1. I Cannot reproduce original "fatal error: concurrent map iteration" issue. So the fix is good.
2.  I Cannot reproduce the new issue "panic: runtime error: invalid memory address or nil pointer dereference". Looks like the new issue only impacting private state, as the log and error suggest "Head private state missing".

ISSUE STILL reproducible for Private contract.

Hope this helps. Thanks

**Comment by frankie-lim-partior** [comment]
@antonydenyer the "panic: runtime error: invalid memory address or nil pointer dereference" still reproducible for private contract. We need to keep this issue open. thanks

**Comment by antonydenyer** [comment]
Understood, can you create a new issue and reference it here?

**Comment by antonydenyer** [comment]
Also reference https://github.com/ConsenSys/quorum/issues/1305 to investigate any performance impact locking may have.

**Comment by frankie-lim-partior** [comment]
This new "panic: runtime error: invalid memory address or nil pointer dereference" issue is introduced as part of the fix for the original " fatal error: concurrent map iteration and map write" error, on the test docker image quorum:fix21.10-3 provided by @baptiste-b-pegasys . So the fix is not complete, the fix introduced new panic issue.

**Comment by antonydenyer** [comment]
Raised a new issue to investigate https://github.com/ConsenSys/quorum/issues/1308

I suspect that what's happening is k8s is killing the pod before it has a chance to write to disk.

**Comment by frankie-lim-partior** [comment]
For Clarity:
1. quorum:fix21.10-3 test image  provided by @baptiste-b-pegasys confirm fixed the "fatal error: concurrent map iteration and map write". I cannot reproduce the issue with the test image.
2. We have never encounter the "panic: runtime error: invalid memory address or nil pointer dereference" before in the official v21.10.0 image. This only first seen on the quorum:fix21.10-3 test image. So this may be an issue introduced by the bug fix code change.
3. The  "panic: runtime error: invalid memory address or nil pointer dereference"  can be reproduced by sending high TPS for private smart contract. I am NOT able to reproduce it in a public smart contract.
4. A second way to reproduce the "panic: runtime error: invalid memory address or nil pointer dereference", is to stop the K8s pod and restart while running with the quorum:fix21.10-3 test image. We can reproduce this 100% of the time on multiple pods. This cannot be reproduced with the official v21.10.0 image. So again it seems to be a bug introduced by quorum:fix21.10-3 test image.

Hopes this helps. thanks
