### ISSUE TITLE
Will smart contract based management of Validators be available?

### ISSUE THREAD

**Issue by YoshihitoAso** [ConsenSys/quorum#1288]
Hi there,

If using QBFT in hyperledger besu, the [management of Validators by smart contract](https://besu.hyperledger.org/en/stable/HowTo/Configure/Consensus-Protocols/Add-Validators/#adding-and-removing-validators-using-a-smart-contract) is available.

Is there any plan to make this available in Quorum?
Or does a similar concept exist in the current Quorum?

**Comment by antonydenyer** [comment]
We're aiming to have this available by the end of q2 this year. We will be using the same smart contracts with the aim of being fully cross-compatible when running QBFT.
