### ISSUE TITLE
Investigate performance impact of lock in state object

### ISSUE THREAD

**Issue by antonydenyer** [ConsenSys/quorum#1305]
Investigate the performance impact (if any) on https://github.com/ConsenSys/quorum/pull/1302 consider moving state object lock higher location where appropriate

**Comment by baptiste-b-pegasys** [comment]
in first round, perf has decreased around 10%

21.10
![Capture du 2022-01-17 16-47-28](https://user-images.githubusercontent.com/85155432/149800720-e9ef7687-f4b8-431a-9ed4-cfc5b5a7a4fe.png)
fixes
![Capture du 2022-01-17 16-33-16](https://user-images.githubusercontent.com/85155432/149800745-68ece9cd-5f84-47eb-8ae7-360ea973bfbe.png)

**Comment by baptiste-b-pegasys** [comment]
second round, result are reversed, 66 TPS for the fixed version, less than 60 for the 21.0

in the end, seems the same to me

21.10
![image](https://user-images.githubusercontent.com/85155432/149803946-b0daa17d-8ce6-428b-9b48-f190ee118e2e.png)

fixes
![image](https://user-images.githubusercontent.com/85155432/149806400-0418d7b2-2045-423d-b023-f755aaee4973.png)

**Comment by antonydenyer** [comment]
Third time lucky?!  ---- On Mon, 17 Jan 2022 16:27:22 +0000  ***@***.***  wrote ----
second round, result are reversed, 66 TPS for the fixed version, less than 60 for the 21.0
in the end, seems the same to me
21.10

fixes

**Comment by baptiste-b-pegasys** [comment]
Comparing in the same computer with enough free CPU ressources
No Change

21.10
![Capture du 2022-01-18 08-46-39](https://user-images.githubusercontent.com/85155432/149898299-26671397-9f01-4792-84de-7a16c011e09e.png)

fixes
![Capture du 2022-01-18 09-19-27](https://user-images.githubusercontent.com/85155432/149898290-4d9990a2-3627-4c75-9aff-91dfafe6cf76.png)
![image](https://user-images.githubusercontent.com/85155432/149898408-6d0e4b74-b20d-446b-ba4a-6ce2c0314d74.png)
![image](https://user-images.githubusercontent.com/85155432/149898561-1c265417-7243-457f-b83d-a12bf88f9aae.png)
![image](https://user-images.githubusercontent.com/85155432/149899186-39863bfb-af95-4cb9-bbb7-55b8f8d3d761.png)

**Comment by baptiste-b-pegasys** [comment]
need the tool (Caliper for Quorum SUT) to check the impact of the lock
