### ISSUE TITLE
flag provided but not defined: -istanbul.blockperiod

### ISSUE THREAD

**Issue by vishnuram1999** [ConsenSys/quorum#1319]
Im trying to start a node in IBFT network of goquorum using geth.

command used:
PRIVATE_CONFIG=ignore geth --datadir data --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --http --http.addr 127.0.0.1 --http.port 22000 --http.api admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul --emitcheckpoints --port 30300

error what I get is
Incorrect Usage. flag provided but not defined: -istanbul.blockperiod

Can someone help me with this.

**Comment by achraf17** [comment]
Can you specify the version of quorum you are using?

**Comment by vishnuram1999** [comment]
Im using 21.10.1

**Comment by antonydenyer** [comment]
The usage looks correct. 
Take a look at  https://consensys.net/docs/goquorum/en/latest/tutorials/quorum-dev-quickstart/getting-started/  it's a better place to start
