### ISSUE TITLE
possibility to run quorum as non-root user

### ISSUE THREAD

**Issue by velenciucsergiu** [ConsenSys/quorum#1323]
hello team

we are trying to run quorum as container on kubernetes. yet, making some inspections/checks, we found out the container is running with root user. wondering if we can switch it to non-root user. if yes, what permissions to which folders it requires access?

Thankyou

**Comment by baptiste-b-pegasys** [comment]
Hello, have you define some security context?

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Comment by velenciucsergiu** [comment]
@baptiste-b-pegasys that's not related to container and pod security context. 
container scanners will just detect the container have the root user running it, and will throw it back with security issue. normally, to fix this gap, we are defining a user on docker level and run the app as non-root. but, the caveat is that, will it fully work with quorum?

**Comment by baptiste-b-pegasys** [comment]
[docker-compose.yml.zip](https://github.com/ConsenSys/quorum/files/8033124/docker-compose.yml.zip)

I don't know which container scanner you use.

I changed my docker compose to be non root, but I have to be root to set my rights on the volume.

If I want to run the container directly as non-root, the volume/directory should be already configured for that user. So the init step should be ran priorly as root, then the docker image as non-root.
