### ISSUE TITLE
Cakeshop not available in quorum-dev-quickstart

### ISSUE THREAD

**Issue by gasipari** [ConsenSys/quorum#1334]
Hi,
After installing the [quorum-dev-quickstart](https://consensys.net/docs/goquorum/en/latest/tutorials/quorum-dev-quickstart/getting-started/)
I can't see the Cakeshop url on localhost. 

JSON-RPC HTTP service endpoint                 : http://localhost:8545
JSON-RPC WebSocket service endpoint        : ws://localhost:8546
Web block explorer address                     : http://localhost:25000/
Blockscout address                             : http://localhost:26000/
Prometheus address                             : http://localhost:9090/graph
Grafana address                                : http://localhost:3000/d/axxxxxx

Any idea why?

Thanks for your help

**Comment by flaskr** [comment]
Apparently the docs are outdated (according to their discord chat) and you should start cakeshop manually
https://github.com/ConsenSys/cakeshop#running-with-the-quorum-dev-quickstart

**Comment by gasipari** [comment]
Thanks for the info @flaskr !
