### ISSUE TITLE
what is member node?

### ISSUE THREAD

**Issue by scalalang2** [ConsenSys/quorum#1355]
According to [qourum-kubernetes](https://github.com/ConsenSys/quorum-kubernetes/tree/master/dev)

We should set up 4 validator node and 1 non-validator node (called member).
In this case. If I configured only 4 validator node. It doesn't propose block at all.

If I add 1 non-validator node. Now they start to propose block.

**Question here.**
1) Why it works like this? My guess is that IBFT consensus doesn't need non-validator node.
2) What is the member node? I cannot found that any explanation.

**Comment by antonydenyer** [comment]
You should probably start here https://consensys.net/docs/goquorum/en/latest/tutorials/quorum-dev-quickstart/getting-started/

A member node is simply someone who is a member of the network but does not not have authority to validate blocks (IBFT is a proof of authority consensus algorithm).

**Comment by scalalang2** [comment]
Thanks it gives me help a lot! : )
