### ISSUE TITLE
Unavailable modules in HTTP API list     unavailable="[trace db shh quorum qbft]"

### ISSUE THREAD

**Issue by pjamenaja** [ConsenSys/quorum#1356]
Hi,

I'm the beginner who's learning to setup GoQuorum by following the instruction in the https://consensys.net/docs/goquorum/en/latest/tutorials/quorum-dev-quickstart/getting-started/.  I got the error below when I ran the "geth". Is there any solution to solve this error? I used "geth" from docker "quorumengineering/quorum:22.1.1".

```
Unavailable modules in HTTP API list     unavailable="[trace db shh quorum qbft]" available="[admin debug web3 eth txpool personal istanbul miner net]"
```

The "geth" command I called was.

```
exec geth \
--datadir ${DATA_FOLDER} \
--nodiscover \
--permissioned \
--verbosity 5 \
${CONSENSUS_ARGS} \
--syncmode full --nousb \
--metrics --pprof --pprof.addr 0.0.0.0 --pprof.port 9545 \
--networkid ${QUORUM_NETWORK_ID:-1337} \
--http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.vhosts "*" --http.api admin,trace,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$QUORUM_API \
--ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins "*" --ws.api admin,trace,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$QUORUM_API \
--port 30303 \
--identity ${HOSTNAME}-${GOQUORUM_CONS_ALGO} \
--unlock ${ADDRESS} \
--allow-insecure-unlock \
--password ${DATA_FOLDER}/keystore/accountPassword \
${ADDITIONAL_ARGS:-} \
2>&1
```

Regards,
James

**Comment by antonydenyer** [comment]
It's nothing worry about, the network will still be running.

**Comment by Lu7Hui7** [comment]
您好，我在写基于区块链的时间银行系统，开启Geth，显示这个
ERROR[03-14|22:29:34.841] Unavailable modules in HTTP API list     unavailable=[db] available="[admin debug web3 eth txpool personal miner net]"，这个对我完成这个项目有影响吗
