### ISSUE TITLE
Can't attach to geth per documentation from quickstart

### ISSUE THREAD

**Issue by luisnaranjo733** [ConsenSys/quorum#1369]
I'm following the [quickstart documentation ](https://consensys.net/docs/goquorum/en/latest/tutorials/quorum-dev-quickstart/using-the-quickstart/#inspect-the-member-nodes-with-geth-attach)to the letter and I can't attach to the geth javascript console

The documentation says to run ```./attach 1``` which fails
<img width="684" alt="image" src="https://user-images.githubusercontent.com/1091547/160508525-93d9ed6d-9de2-43c2-8cf4-94bcd1987d8f.png">

If I run the underlying docker command manually, I get the same result
```docker-compose exec member1quorum /bin/sh -c "geth attach /data/dd/geth.ipc"```

I can tweak the underlying docker command to connect to the 8545 RPC endpoint (which actually works)
```docker-compose exec member1quorum /bin/sh -c "geth attach http://localhost:8545"```

But that's not what I'm trying to do. I'm trying to learn how to attach to all 3 GoQuorum nodes for testing private transaction functionality. Any idea why this is happening?

**Comment by archm49** [comment]
@antonydenyer

**Comment by antonydenyer** [comment]
Will get released in the next version. 

`docker-compose exec member1quorum /bin/sh -c "geth attach /data/geth.ipc"`

Should do the trick. Thanks for reporting.
