### ISSUE TITLE
Is Cakeshop being taken down?

### ISSUE THREAD

**Issue by leeronkit** [ConsenSys/quorum#1370]
Is CakeShop being taken down? Cant seems to find the cakeshop endpoint. Cant access too after following the manual guide
https://github.com/ConsenSys/cakeshop#running-with-the-quorum-dev-quickstart

**Comment by antonydenyer** [comment]
We're moving away from cakeshop to use more off the shelf solutions that are not bespoke to GoQuorum https://github.com/ConsenSys/quorum-dev-quickstart/issues/135 

I've updated the readme on https://github.com/ConsenSys/cakeshop#running-with-the-quorum-dev-quickstart 

Please re-open if further clarification is needed.
