### ISSUE TITLE
look here,I'll tell whoever invites me to have ice cream

### ISSUE THREAD

**Issue by oooomoooo** [ConsenSys/quorum#1410]
Fatal: Consensus not specified. Exiting

**Comment by baptiste-b-pegasys** [comment]
Thank you for raising this, I think `--datadir` is part of the command line of geth inside the docker container, not your directory from your local computer. I guess it's not really a proper way to use goquorum, we should update this.

Take a look at quorum examples, with a docker compose file you can mount/copy your local directory and add the geth init step that is an important part.
https://github.com/ConsenSys/quorum-examples/blob/master/docker-compose.yml

**Comment by oooomoooo** [comment]
Thank you. In fact, it doesn't need to be so complicated. I solved it three days ago. I still have a simple way to deal with it. However, I'll tell whoever invites me to have ice cream
