### ISSUE TITLE
Metrics Data issue : P2P metrics values are high

### ISSUE THREAD

**Issue by smvdn** [ConsenSys/quorum#1418]
#### System information

Geth version: `1.9.24-stable`
OS & Version: Windows/Linux
Quorum Version: 21.7.1

#### Expected behaviour
The P2P_Peers metric for quorum nodes should have a co-relation with net.PeerCount value.

#### Actual behaviour

P2P_Peer Count is always higher than twice the value of net.PeerCount.

##### Net Peer Count result
> net.peerCount
6
##### p2p_peers metrics result
```
 curl -sS http://localhost:metricsport/debug/metrics/prometheus | grep "p2p_peers" -i
# TYPE p2p_peers gauge
p2p_peers 13
```
Also is there a document depicting different metrics & its details available on Quorum.

**Comment by baptiste-b-pegasys** [comment]
thank you, one possible reason is that there is an error occurring while closing the peer connection, the metered gauge doesn't decrement the count when there is an error, while p2p.server doesn't check the error at all, therefore the count is certainly decremented.

This is the actual implementation of go-ethereum, so I will apply a PR on geth side to check if it is a bug.

https://github.com/ethereum/go-ethereum/blob/master/p2p/server.go#L881
https://github.com/ethereum/go-ethereum/blob/master/p2p/metrics.go#L90

**Comment by smvdn** [comment]
thanks for the response. Does the p2p_peers metrics not considering unique peers connected ? If its taking unique peer count (using enode address) even while reconnecting due to error the counter shouldn't increase right ?

**Comment by baptiste-b-pegasys** [comment]
Hello, do you have an idea how to reproduce your case. I stopped, killed and paused a node's container, the two counters behave correctly.
Demand on the geth side too, they want to reproduce the case.
Thank you
