### ISSUE TITLE
error when starting geth

### ISSUE THREAD

**Issue by ForLina** [ConsenSys/quorum#1435]
I followed the guide https://consensys.net/docs/goquorum/en/latest/tutorials/private-network/create-qbft-network/ to deploy private networks, these are  errors I met.

1.when started Node0, I got an error as follow:
`
INFO [06-15|14:35:58.713] Security Plugin is not enabled 

ERROR[06-15|14:35:58.713] Unavailable modules in HTTP API list     unavailable="[trace db shh quorum qbft]" available="[admin debug web3 eth txpool personal istanbul miner net]"

ERROR[06-15|14:35:58.713] Unavailable modules in HTTP API list     unavailable="[trace db shh quorum qbft]" available="[admin debug web3 eth txpool personal istanbul miner net]"
`

2.there is some typing error in part 7 '7. Start nodes 1, 2, 3, and 4', in node2, it says: 

`export ADDRESS=$(grep -o '"address": *"[^"]*"' ./data/keystore/accountKeystore | grep -o '"[^"]*"$' | sed 's/"//g')

export PRIVATE_CONFIG=ignore

geth --datadir data \
    --networkid 1337 --nodiscover --verbosity 5 \
    --syncmode full --nousb \
    --istanbul.blockperiod 5 --mine --miner.threads 1 --miner.gasprice 0 --emitcheckpoints
    --http --http.addr 127.0.0.1 --http.port 22002 --http.corsdomain "*" --http.vhosts "*" \
    --ws --ws.addr 127.0.0.1 --ws.port 32002--ws.origins "*" \
    --http.api admin,trace,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul,qbft \
    --ws.api admin,trace,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul,qbft \
    --unlock ${ADDRESS} --allow-insecure-unlock --password ./data/keystore/accountPassword \
    --port 30302`

 a.there should be a '\\'  after '--emitcheckpoints' 
 b.there should be a space between  '32002' and '--ws.origins'

3.In part 9, net.peerCount equals 0, I checked everything, but i still can't the problem.

**Comment by baptiste-b-pegasys** [comment]
thank you, will work on PR for documentation.

**Comment by ForLina** [comment]
I wonder if the author verified the guide? Cuz I followed the guide step by step but got net.peerCount = 0 ?

**Comment by baptiste-b-pegasys** [comment]
you're right, I can reproduce the peer count issue.
The node 3 is OK with the peer count with 4 , however the others have 1
I don't have 0

**Comment by baptiste-b-pegasys** [comment]
Ok it is explained in the section for my case.

Here is the mistake I made:
```
[
  "enode://e8309522c711edce6ac0a2cd7d85ca9d8c87c93540af6e6b27d9a993ff20f7bfe63337ebb2bade6f1fdfb006b88cd697b3a6ebc982d87a5a756598ef8abe7aeb@localhost:30303?discport=0&raftport=53000",
  "enode://5888e4a989b8adbce72e43445ae74046b9be7ac702ed5cbc21030911a78a86bc4a3015ce38f2184b48e79462bf71c829967ca5261d41128c93cd9dc2815a1657@localhost:30303?discport=0&raftport=53000",
  "enode://bf2c732ae094d2698caf0167befc288e408c37564a3be44e5867becce887b1946475c282c50615b5f4198b3435328daa936cb926478c97b9f9013686e1862b00@localhost:30303?discport=0&raftport=53000",
  "enode://015391c14a96ef10473d741080de6dc77f98f3e2087d44160c2658b7011c86cf69671bdfae2d50624194d525fa4f1d9d71066fd8769feb24f6e57fba0786d51e@localhost:30303?discport=0&raftport=53000",
  "enode://70c2f65d7c92eaf3b58c419b23a2e0c0ad067be367eec19425048a1b012ffb9ba6fb4ee645cbb5060e39891264a38ff52343f1a16e9fe4b7f2b36d8ac24ffd13@localhost:30303?discport=0&raftport=53000"
]
```

I filled the address but forgot to change the port accordingly.

I noted that for macos, `localhost`has to be used instead of `127.0.0.1`

**Comment by ForLina** [comment]
Hi, I got same error when I tried to deploy IBFT network.  
`ERROR[06-16|09:04:48.550] Unavailable modules in HTTP API list     unavailable="[trace db shh quorum]" available="[admin debug web3 eth txpool personal istanbul miner net]"

ERROR[06-16|09:04:48.550] Unavailable modules in HTTP API list     unavailable="[trace db shh quorum]" available="[admin debug web3 eth txpool personal istanbul miner net]"
`

https://consensys.net/docs/goquorum/en/latest/tutorials/private-network/create-ibft-network/

**Comment by baptiste-b-pegasys** [comment]
sure, it's more a warning than an error, will fix ibft too when qbft get validated
