### ISSUE TITLE
Error in Quorum node sync post disk space became full in the server

### ISSUE THREAD

**Issue by Purbaja** [ConsenSys/quorum#1437]
In a UAT environment where we had a quorum network with 4 nodes running in separate vms.
Suddenly one vm's disk got full. 
Once noticed, before extending the disk, we tried to stop the quorum containers but unable to do that due to full disk space issue.
Steps performed for increasing the quorum disk.
•	Stopped the VM and increased the Disk 
•	Started the VM But the Azure agent went into a NOT READY state. 
•	In order to get back the VM we need to free up some space, So we have deleted a docker log file and replaced back after expansion of the disk.
After that when the node was up, we observed that the block height is not syncing (it was lagging by ~50 blocks),  we checked the following
•	raft.cluster – we are able to see all the nodes
•	admin.peers – we are able to other peers.
•	eth.syncing – false

	We tried restarting the node but didn’t helped.
Please guide us for some feasible solution.

**Comment by antonydenyer** [comment]
if your db is corrupted the best thing to do is resync the node.
