### ISSUE TITLE
Custom error messages not being displayed

### ISSUE THREAD

**Issue by DanDinjian** [ConsenSys/quorum#1447]
Discovered in Chainstack Quorum deploy and reproduced locally with Quorum v22.4.4

```
  function myFunc() returns (bool) {
    require(hasPermission(), "Custom Error Message");
    return true;
  }
```

If a require like this is failed on geth or a local hardhat node, the error message thrown will have the custom error message in the reason, but in quorum the error message thrown is always an UNPREDICTABLE_GAS_LIMIT error approximately below.  
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit
[ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ]
(error=
  {
  "reason":"cannot estimate gas; transaction may fail or may require manual gas limit",
  "code":"UNPREDICTABLE_GAS_LIMIT",
  "error":
    {"reason":"processing response error","code":"SERVER_ERROR","body":"{...}"}
  }
)
```

This is obfuscating and misleading half of our dev team that's less familiar with the solidity error cases because they have no idea what they're doing wrong.

**Comment by antonydenyer** [comment]
Have you got revert reason enabled? https://consensys.net/docs/goquorum/en/latest/configure-and-manage/manage/revert-reason/

Which endpoint are you calling?

**Comment by DanDinjian** [comment]
Using `require`, not `revert` but the docs suggest it should still work.

Using `pragma solidity ^0.8.0;`

Not certain what you mean by endpoint

**Comment by antonydenyer** [comment]
`require` will throw an exception that will cause the transaction to revert. So you need to have revert reason enabled.

Which RPC endpoint are you using, `eth_call`, `eth_sendRawTransaction`? What does the actual rpc request look like (i.e can you reproduce using curl)? 

I suspect it's something to do with ethers trying to submit an eip 1559 transaction which GoQuorum doesn't support yet. But without more information we don't know.

**Comment by DanDinjian** [comment]
The issue appears in the `estimateGas` call, estimating gas fails because there's a `require` clause being failed (which is correct, we want the code to error this way to say you can't do something you're not supposed to).

The error message is a bit unwieldly and I'm not certain what all of the nested iterations of my function are included for.  But basically, nested somewhere in this stack I would expect to see my custom error message that comes from the `require` responsible for the failing transaction.

```
Uncaught (in promise) Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"Execution reverted","code":"UNPREDICTABLE_GAS_LIMIT","method":"estimateGas","transaction":{"from":"0x90F79bf6EB2c4f870365E785982E1f101E93b906","gasPrice":{"type":"BigNumber","hex":"0x00"},"to":"0x5FbDB2315678afecb367f032d93F642f64180aa3","data":"0xdf707022000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000000355534400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016372f31332f323032322c2031313a34373a343020414d000000000000000000000000000000000000000000000000000000000000000000000000000000000000","accessList":null},"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\n  \"jsonrpc\" : \"2.0\",\n  \"id\" : 52,\n  \"error\" : {\n    \"code\" : -32000,\n    \"message\" : \"Execution reverted\",\n    \"data\" : \"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002b416363657373436f6e74726f6c3a2073656e646572206d7573742068617665206d696e74657220726f6c65000000000000000000000000000000000000000000\"\n  }\n}","error":{"code":-32000,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002b416363657373436f6e74726f6c3a2073656e646572206d7573742068617665206d696e74657220726f6c65000000000000000000000000000000000000000000"},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x0\",\"from\":\"0x90f79bf6eb2c4f870365e785982e1f101e93b906\",\"to\":\"0x5fbdb2315678afecb367f032d93f642f64180aa3\",\"data\":\"0xdf707022000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000000355534400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016372f31332f323032322c2031313a34373a343020414d000000000000000000000000000000000000000000000000000000000000000000000000000000000000\"}],\"id\":52,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://localhost:8545"}}, tx={"data":"0xdf707022000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000000355534400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016372f31332f323032322c2031313a34373a343020414d000000000000000000000000000000000000000000000000000000000000000000000000000000000000","to":{},"from":"0x90F79bf6EB2c4f870365E785982E1f101E93b906","gasPrice":{"type":"BigNumber","hex":"0x00"},"type":0,"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.6.2)
    at Logger.makeError (index.ts:261:1)
    at Logger.throwError (index.ts:273:1)
    at index.ts:301:1
    at async Promise.all (index 6)
```

**Comment by antonydenyer** [comment]
`0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002b416363657373436f6e74726f6c3a2073656e646572206d7573742068617665206d696e74657220726f6c65000000000000000000000000000000000000000000`

Is the `revertReason` it's up to ethers js to figure out how to decode it.

**Comment by DanDinjian** [comment]
According to [this link](https://consensys.net/docs/goquorum/en/latest/configure-and-manage/manage/revert-reason/) and the solidity documentation, the error string `"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001a4e6f7420656e6f7567682045746865722070726f76696465642e000000000000"` is the encoded version of `"Not enough Ether provided."

I've been using [ethers.utils.defaultAbiCoder.decode](https://docs.ethers.io/v5/api/utils/abi/coder/) to try many ways to reproduce the `"Not enough Ether provided."` error message from the encoded error and I am unable to get it.

Among other things I've tried decoding just the String data with `ethers.utils.defaultAbiCoder.decode(['string'], "0x4e6f7420656e6f7567682045746865722070726f76696465642e000000000000")`, `decode([4 types], full_encoded_error_string)`, `decode(['string'], full_encoded_error_string)`.

When I try to decode a string I'm getting this numeric overflow error `Uncaught Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="toNumber", value="3963877391197344453575983046348115674221700746820753546331534351508065746944", code=NUMERIC_FAULT, version=bignumber/5.6.2)` which I don't understand because I'm not trying to convert anything into a number.

I know interpreting `revertReason` is a common difficulty in the blockchain but I am just trying to reverse engineer the encoding on the default `"Not enough Ether provided"` error message.  How do I reconstruct that error message from the encoded error string?

**Comment by antonydenyer** [comment]
You need to raise that with ethers-io
