### ISSUE TITLE
Configure block rewards on a QBFT network deployment

### ISSUE THREAD

**Issue by antonydenyer** [ConsenSys/quorum#1471]
Enable block rewards to be configurable

```
{
  "config": {
     ...
     "qbft": {
       "blockPeriodSeconds": 2,
       "blockReward": "5000000000000000"
     },
     "transitions":  [
       {
         "block": <FutureBlockNumber>,
         "blockReward": <NewValue>
       }
     ]
  },
  ...
}
```

The rewards should go to the miner coinbase as normal

- [x] Update code
- [x] Update QAT and PEEPS
- [x] Update docs

**Comment by baptiste-b-pegasys** [comment]
add a mode (validators auto filled list), and a manual list of beneficiary

**Comment by yangmiok** [comment]
> add a mode (validators auto filled list), and a manual list of beneficiary

can you give me an example？
