### ISSUE TITLE
Transaction in private blockchain

### ISSUE THREAD

**Issue by LYAMZAYA** [ConsenSys/quorum#1474]
Hello, i made private blockchain, but when i want to do transaction i get this: 

`personal.sendTransaction({from:["0x6430a3ECab5752BbAb37Cea8796afe44Fc8531DD], to["0xEc31fda0398e2CD90Ec7928c797582b169C4E978"], value: web3.toWei(1233231, "ether")})`
...... 
...... 
...... 

What is this mean? I did not find an answer on the Internet

**Comment by chris-j-h** [comment]
You have some typos: close your quotes, `from` and `to` are strings not lists, make sure you're not missing any `:`.  

Also, most of the `personal` APIs expect your account password passed as the final arg.  If your account is unprotected you don't need to worry about it but that's not recommended other than dev testing.

```diff
- personal.sendTransaction({from:["0x6430a3ECab5752BbAb37Cea8796afe44Fc8531DD], to["0xEc31fda0398e2CD90Ec7928c797582b169C4E978"], value: web3.toWei(1233231, "ether")})
+ personal.sendTransaction({from:"0x6430a3ECab5752BbAb37Cea8796afe44Fc8531DD", to:"0xEc31fda0398e2CD90Ec7928c797582b169C4E978", value:web3.toWei(1233231, "ether")}, "myacctpwd")
```

Use the web3js documentation for examples of the standard geth APIs https://web3js.readthedocs.io/en/v1.7.5/web3-eth-personal.html#sendtransaction.  Quorum specific API info can be found in the quorum docs.

**Comment by LYAMZAYA** [comment]
TY very much, i used wrong website's, for the info
