### ISSUE TITLE
Updating go-ethereum

### ISSUE THREAD

**Issue by coltonfreeman26** [ConsenSys/quorum#1476]
Good morning all,

I did notice the quorum bot opened an issue to update go-ethereum but was wondering if you could bump it to the latest release?
- https://github.com/ethereum/go-ethereum/tags

W/r Colton

**Comment by baptiste-b-pegasys** [comment]
Hello, work is in progress for upgrading v1.10.3

**Comment by coltonfreeman26** [comment]
Thank you.

**Comment by antonydenyer** [comment]
https://github.com/ConsenSys/quorum/pull/1469
