### ISSUE TITLE
Unable to `delegatecall` from a private proxy to a public implementation

### ISSUE THREAD

**Issue by frank-lim-partior** [ConsenSys/quorum#1489]
#### System information

Geth version: `[https://github.com/ConsenSys/quorum-dev-quickstart](https://github.com/ConsenSys/quorum-dev-quickstart/commit/fa2c4f2038ebdf54ef962e5e7d44bfd444ebb1d8)`
OS & Version: OSX 12.5.1

#### Expected behaviour
In a private txn, a `delegatecall` from a private proxy to a public implementation does not modify public contract state and should not fail.

#### Actual behaviour
EVM reverts the delegatecall transaction.

#### Steps to reproduce the behaviour
1. Deploy quorum-dev-quickstart network
2. Drop attached contract files and scripts into respective folders in `quorum-test-network/smart-contracts/privacy`
3. Install forge-foundry
4. run `forge build` inside the `privacy` project folder to generate jsons
5. run `node scripts/delegate_call_from_priv.js`
* Deploy `StorageLogic` as public
* Deploy `StorageProxy` as private between 1+3
* scriptName: `delegate_call_from_priv.js`
    * :white_check_mark: Call `pureGet()` on private `StorageProxy` - this is ok
    * :x: Call `set()` on private `StorageProxy` to update value to 223
       * Transaction is reverted on `delegatecall` - this is not ok
7. observe that `delegatecall` for a pure function works, but not a set function, even if it does not modify public state.

#### Backtrace

````
[delegate_failed.zip](https://github.com/ConsenSys/quorum/files/9443691/delegate_failed.zip)

[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by antonydenyer** [comment]
Based on the example provided this is correct behaviour. You can not change public state from a private contract. If you attempt to do this the transaction will be reverted. You can query public state whilst changing private state int he same method call. 

If you still thing there is a bug there please re-open with a clearer example.

**Comment by frank-lim-partior** [comment]
hi @antonydenyer, as mentioned, a `delegatecall` to a public contract can not change the state of the call-ee public contract, no matter what the function does (unless it issues a state-changing `call` to another public contract).

If you try out my contracts in remix, you will see that the public contract (StorageLogic.sol) values remain unchanged in my test scenario.

Can you perhaps provide some references to how quorum decides if a call involves a public state change?

**Comment by frank-lim-partior** [comment]
The answer did not resolve the issue. There is still a clear mismatch between docs and observed behavior.

**Comment by antonydenyer** [comment]
You can not call anything that changes state from a private contract to a public one. The very act of performing a transaction is changing state. Calling the function to set the value even to the same value is changing public state.

**Comment by frank-lim-partior** [comment]
Like I mentioned, the `delegatecall` of a private contract can not change the state of the public contract. The code of the public contract operates with the state of the private contract. 

In the below remix example, Contract A can be thought of as the private contract, and Contract B as the public contract. Try
1. Deploy B
2. Deploy A
3. call `A.num()` (0 - private state initial value)
4. call `B.num()` (0 - public state initial value)
5. call `A.setVars(addressB, 100)` (A does a delegatecall to a setter in addressB)
6. call `A.num()` (100 - private state updated)
7. call `B.num()` (0 - public state untouched)

https://solidity-by-example.org/delegatecall/
[Delegatecall.sol](https://remix.ethereum.org/?#code=Ly8gU1BEWC1MaWNlbnNlLUlkZW50aWZpZXI6IE1JVApwcmFnbWEgc29saWRpdHkgXjAuOC4xMzsKCi8vIE5PVEU6IERlcGxveSB0aGlzIGNvbnRyYWN0IGZpcnN0CmNvbnRyYWN0IEIgewogICAgLy8gTk9URTogc3RvcmFnZSBsYXlvdXQgbXVzdCBiZSB0aGUgc2FtZSBhcyBjb250cmFjdCBBCiAgICB1aW50IHB1YmxpYyBudW07CiAgICBhZGRyZXNzIHB1YmxpYyBzZW5kZXI7CiAgICB1aW50IHB1YmxpYyB2YWx1ZTsKCiAgICBmdW5jdGlvbiBzZXRWYXJzKHVpbnQgX251bSkgcHVibGljIHBheWFibGUgewogICAgICAgIG51bSA9IF9udW07CiAgICAgICAgc2VuZGVyID0gbXNnLnNlbmRlcjsKICAgICAgICB2YWx1ZSA9IG1zZy52YWx1ZTsKICAgIH0KfQoKY29udHJhY3QgQSB7CiAgICB1aW50IHB1YmxpYyBudW07CiAgICBhZGRyZXNzIHB1YmxpYyBzZW5kZXI7CiAgICB1aW50IHB1YmxpYyB2YWx1ZTsKCiAgICBmdW5jdGlvbiBzZXRWYXJzKGFkZHJlc3MgX2NvbnRyYWN0LCB1aW50IF9udW0pIHB1YmxpYyBwYXlhYmxlIHsKICAgICAgICAvLyBBJ3Mgc3RvcmFnZSBpcyBzZXQsIEIgaXMgbm90IG1vZGlmaWVkLgogICAgICAgIChib29sIHN1Y2Nlc3MsIGJ5dGVzIG1lbW9yeSBkYXRhKSA9IF9jb250cmFjdC5kZWxlZ2F0ZWNhbGwoCiAgICAgICAgICAgIGFiaS5lbmNvZGVXaXRoU2lnbmF0dXJlKCJzZXRWYXJzKHVpbnQyNTYpIiwgX251bSkKICAgICAgICApOwogICAgfQp9Cg==)

**Comment by antonydenyer** [comment]
> The code of the public contract operates with the state of the private contract.

A public contract can not interact with a private contract.

A private contract can only read from a public contract.

You can not use delegateCall from a private contract to a public one because the contract is private and in affect you are delgating to the public contact and saying you, public contract, can do things to my private storage. You can use `call` but you can not use `delegateCall`

**Comment by frank-lim-partior** [comment]
I was able to use `delegatecall` to a public contract when calling a function with `view`, which allowed the public contract's code return the private contract's state. We are essentially allowing the private contract to read the public contract's code to reuse it.

Can you define what is meant by "interact with a private contract"?

Even if it doesn't work now, what's the rationale behind disallowing this?
