### ISSUE TITLE
[Alastria T network] · Failed to start synchronization

### ISSUE THREAD

**Issue by alejandroalffer** [ConsenSys/quorum#1585]
Hello!

After the network shutdown, some validator nodes do not re-synchronize with the blockchain, to reach the last block, even though it is downloaded.

```
> admin.nodeInfo.name
"Geth/VAL_DigitelTS_T_4_16_00/v1.9.25-stable-919800f0(quorum-v21.10.0)/linux-amd64/go1.15.6"
> admin.nodeInfo.id
"ae385305ccad4d035e92efbfebc69e585b93f293e6552a0110afc196d90105dd"
> eth.blockNumber
106919851
> eth.syncing
false
> eth.getBlockByNumber(106919851)
{
  difficulty: "0x1",
  extraData: "intentionally supressed",
  gasLimit: "0x29b154ca",
  gasUsed: "0x0",
[...]



> eth.blockNumber
106919851
> eth.getBlockByNumber(106983272)
{
  difficulty: "0x1",
[...]
  gasLimit: "0x29b3f008",
  gasUsed: "0x1378d94",
[...]
}



> eth.getBlockByNumber(106983273)
null
```

I have tried different debug commands without success

Any way to force the last few blocks to sync?

All the details in https://github.com/alastria/alastria-node-quorum/issues/38

All the best!

**Comment by baptiste-b-pegasys** [comment]
Hello, have you resolved this ticket ? https://github.com/alastria/alastria-node-quorum/issues/38#issuecomment-1356855566

I took a look at what's been done in the alaquorum project, is this commit that resolves the problem (about hardcoded gaslimit) ? https://github.com/hesusruiz/alaquorum/commit/810fa8436a3517af4af82bc738a090a64815b726

We worked on the gas limit issue in this PR: https://github.com/ConsenSys/quorum/pull/1448/files

or is this something else?

**Comment by irzinfante** [comment]
Solution achievable with a transition thanks to changes introduced in https://github.com/ConsenSys/quorum/pull/1448/files only let the block gasLimit to go down until 700M units of gas, but not lower.

Changes introduced to the GoQuorum client in https://github.com/hesusruiz/alaquorum/commit/810fa8436a3517af4af82bc738a090a64815b726 hardcode the effective limit of gas for every block, after a particular block of our T Network in Alastria (https://github.com/alastria/alastria-node-quorum), to 30M units of gas.

About the issue https://github.com/alastria/alastria-node-quorum/issues/38, validators of T Network lost peering for some time, and when activity resumed the txpool was so big that blocks of almost 700M units of gas were being proposed, which were too big to process... so a hardcoded limit of 30M was needed to resume block production.
