### ISSUE TITLE
raft_addPeer returns duplicate raft id

### ISSUE THREAD

**Issue by robinbryce** [ConsenSys/quorum#1592]
#### System information
Geth
Version: 1.10.3-stable
Git Commit: d318a5aa973a7ac5edd09798870ed86060af14d8
Quorum Version: 22.7.4
Architecture: amd64
Network Id: 1337
Go Version: go1.16.15
Operating System: linux
GOPATH=
GOROOT=go

Nodes all hosted in azure. 

#### Expected behaviour

Given a new network that looks like this,

static-nodes.json
        "enode://8334f9e52d3be971ea8472e7da6d966f2cc575eb7560d527d93da1a6aeb737f4313be41b9514049b21eb441240db7ecce18b4e95adf63b1e1472e15c436a5cd8@104.40.129.4:21000?discport=0&raftport=50400",
        "enode://989992ac3d6c27d25ddd4485aa68e892c327dffd50339608252d5263ebd5cba7b1acfbb65fb3376e0d0f094c088b966123266c0b1fbd0c2d5028e28f05004e0b@104.40.129.23:21000?discport=0&raftport=50400",
        "enode://618f8e797f44d02c7fb9cdc0ddb03a28c80cfc83109a4fe3c4178e01b2bb9b416d912c6581051bf0e466e212464ccf09365390ee6f80414a1a28274faa6c17bc@104.40.194.48:21000?discport=0&raftport=50400"
		
		
Where the raft ids of each, according to raft.cluster at the shell, are 1, 2, 3 respectively.
			
If I invoke raft_addPeer from a new node init container

	connecting to http://104.40.129.4:22000
	request: {jsonrpc="2.0", method="raft_addPeer", params=["node://178ac76fc92d6002f128f0979f48b8f669f89bdbef17548a8a4b097c12b746a78348ba92b0f3a1b4949411651b81c51b0e8377786263613e48bf5cfcba9bee1a@104.40.194.48:21001?discport=0&raftport=50401"], id="33"}

I expect to get 4 as  the raft id response

#### Actual behaviour

I get 3

#### Steps to reproduce the behaviour

* Setup a local docker networking environment which allows for static 3 static ip addresses
* create the first node
* create the next two nodes in turn, calling raft_addPeer, and then running geth with --joinexisting raftid
* These first 3 nodes each get a unique IP address

* When each successive node is added, call raft_addPeer on the first created, then use geth --joinexisting with the obtained raft id
* For each node that is added, ensure that the static-nodes.json includes all previous nodes (but don't update the previously created nodes)

* Create the 4rth node. give it the same IP as the 3rd node, but use a different port

**Comment by robinbryce** [comment]
Ok, I think the anser is probably `"For a Raft network to work, 51% of the peers must be up and running"` as per the important note at the end of this reference. https://consensys.net/docs/goquorum/en/latest/tutorials/private-network/create-a-raft-network/#9-add-more-nodes

I will close this in a day or so if we can confirm that

**Comment by antonydenyer** [comment]
> Ok, I think the anser is probably `"For a Raft network to work, 51% of the peers must be up and running"` as per the important note at the end of this reference. https://consensys.net/docs/goquorum/en/latest/tutorials/private-network/create-a-raft-network/#9-add-more-nodes
> 
> I will close this in a day or so if we can confirm that

Generally speaking raft is crash tolerant but not fault tolerant. So when you get into a split brain/forked state you can't recover without manual intervention. As a rule of thumb we recommend you use QBFT first and if that isn't meeting your needs evaluate raft.

**Comment by robinbryce** [comment]
Thanks for the info. Closing this now though. It was definitely the 'peers not up' issue in this instance
