### ISSUE TITLE
How to mint in exsitted network?

### ISSUE THREAD

**Issue by kth-tw** [ConsenSys/quorum#1600]
I have a private QBFT quorum network. If I didn't set alloc in genesis file when create network, is any way to mint token?

**Comment by baptiste-b-pegasys** [comment]
Hi you can check block rewards.
You can set blockReward to one fixed account, amount will be added per each block validated.
https://docs.goquorum.consensys.net/configure-and-manage/configure/consensus-protocols/qbft#rewards
