### ISSUE TITLE
QBFT consensus randomly stops working and a chain fork occurs when emptyblockperiodseconds is enabled

### ISSUE THREAD

**Issue by hhsel** [ConsenSys/quorum#1630]
#### System information

Geth version:
```
Version: 1.10.3-stable
Git Commit: 28721bf9f2a66e3f77344bfe2242e7e079245229
Quorum Version: 22.7.6
```
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
Empty blocks are produced constantly without any problems while emptyblockperiodseconds is enabled and no transactions are sent.

#### Actual behaviour
If emptyblockperiodseconds is enabled and let a cluster produce empty blocks for some time without sending transactions,
consensus randomly stops working and unexpected fork occurs, leaving the cluster stuck at a round change loop forever.
The only way to recover is isolating each nodes and executing debug.setHead() on each node to rollback to the previous block.

#### Steps to reproduce the behaviour
1. Start a new goquorum v22.7.6 cluster, enable emptyblockperiodseconds by setting it whatever interval you wish it to be (I experienced this with 60 seconds and 10 seconds and blockperiodseconds set to 1, for example)
   I have confirmed this occurs on four-node AWS EC2 and four-node docker compose (Windows) environments.
   Attached docker-compose.yaml, genesis.json and entrypoint.sh is just an example. genesis.json was just generated from quorum-genesis-tool.
2. Let the cluster produce empty blocks without sending any transactions for some days or weeks.
3. Consensus randomly stops working in a unexpected way with "Chain reorg detected" log, leaving cluster nodes stuck at round change state forever.
In my cases the cluster stopped working at approx. 18,000 blocks (about 2 weeks with 60 emptyblockperiodseconds) and 13,000 blocks (a few days with 10 emptyblockperiodseconds), for example.

Logs are attached as node01.log ～ node04.log, from block number 13208 to 13210, where the fork occured.
The logs suggest almost identical behavior reported in #1612, the only difference being whether I have enabled emptyblockperiodseconds.
The proposed fix in #1612 seems to have no effect if emptyblockperiodseconds is enabled.

Validators successfully produce empty blocks for some time (13209 in this case).
At each block, the proposer of a block waits for emptyblockperiodseconds and after that, it broadcasts PRE-PREPARE message.
```
docker-compose-node02-1  | INFO [03-26|06:37:01.837] QBFT: start new round                    address=0xa6Fb24E8311b540182f015E3F254fF18382D655B old.round=0  old.sequence=13208 old.state=Committed        old.proposer=0xB13c8245DE0a160B22A538DfCbce0ed053f0107D next.round=0 next.seq=13209 next.proposer=0xa6Fb24E8311b540182f015E3F254fF18382D655B next.valSet="[0x8D3827476c3854257D20dA89Cac6E644622910bF 0xB13c8245DE0a160B22A538DfCbce0ed053f0107D 0xa6Fb24E8311b540182f015E3F254fF18382D655B 0xabC8508cE4cECfc03938c5E2ee181bE5578ed1DB]" next.size=4 next.IsProposer=true
docker-compose-node02-1  | INFO [03-26|06:37:01.837] QBFT: handle block proposal request      address=0xa6Fb24E8311b540182f015E3F254fF18382D655B current.round=0 current.sequence=13209 state="Accept request"
docker-compose-node02-1  | INFO [03-26|06:37:01.837] EmptyBlockPeriod detected adding delay to request EmptyBlockPeriod=10 BlockTime=1,679,812,621
↓ waits for emptyblockperiodseconds and proposes a block freshly minted at the current block height, good.
docker-compose-node02-1  | INFO [03-26|06:37:10.837] QBFT: broadcast PRE-PREPARE message      address=0xa6Fb24E8311b540182f015E3F254fF18382D655B current.round=0 current.sequence=13209 state="Accept request" msg.code=18 msg.source=0xa6Fb24E8311b540182f015E3F254fF18382D655B msg.round=0 msg.sequence=13209 block.number=13209 block.hash=0x0f45db99fb2188cdce51e33f28d8739c654bc2fdae73d2e188f49f6d46a02097 payload=0xf902ccf902c6f9028082339980f90279f90274a0098828b5ef5d9f5c44e8575a00bf94cd1ccd09e78298917d4a06f2fd8107c48da01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d4934794a6fb24e8311b540182f015e3f254ff18382d655ba0364b8d1f9f3c1404d15bbe78b47afada7da1297b3dd7d090f0b82ec79af6ab62a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018233998429b927008084641fe80db87cf87aa0d883010a03846765746888676f312e31392e35856c696e757800000000000000f854948d3827476c3854257d20da89cac6e644622910bf94a6fb24e8311b540182f015e3f254ff18382d655b94abc8508ce4cecfc03938c5e2ee181be5578ed1db94b13c8245de0a160b22a538dfcbce0ed053f0107dc080c0a063746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365880000000000000000c0c0b841b36322a942aaee17e7310c03e05d06de018c7c3f7b5162409dde6f7448a853b54717c6a5477c6c4a756ad5a0a9bb48d44a3e6bee668096652745647a7a0fde2e01c2c0c0
```
But in the next block number (13210), the proposer (node 1 in this case) immediately proposes the block which the node have mined in its own at the previous block number.
```
docker-compose-node01-1  | INFO [03-26|06:37:01.837] Commit new mining work                   number=13209 sealhash=e836b8..08ab71 uncles=0 txs=0 gas=0 fees=0 elapsed="83.334µs"
...
docker-compose-node01-1  | INFO [03-26|06:37:10.841] Commit new mining work                   number=13210 sealhash=61e079..8e9191 uncles=0 txs=0 gas=0 fees=0 elapsed="94.839µs"
docker-compose-node01-1  | INFO [03-26|06:37:10.841] QBFT: handle final committed             address=0xabC8508cE4cECfc03938c5E2ee181bE5578ed1DB current.round=0 current.sequence=13209 state=Committed
docker-compose-node01-1  | INFO [03-26|06:37:10.841] QBFT: initialize new round               address=0xabC8508cE4cECfc03938c5E2ee181bE5578ed1DB current.round=0 current.sequence=13209 target.round=0 lastProposal.number=13209 lastProposal.hash=0f45db..a02097
docker-compose-node01-1  | INFO [03-26|06:37:10.841] QBFT: changed state                      address=0xabC8508cE4cECfc03938c5E2ee181bE5578ed1DB current.round=0 current.sequence=13210 old.state=Committed        new.state="Accept request"
docker-compose-node01-1  | INFO [03-26|06:37:10.841] QBFT: start new round                    address=0xabC8508cE4cECfc03938c5E2ee181bE5578ed1DB old.round=0  old.sequence=13209 old.state=Committed        old.proposer=0xa6Fb24E8311b540182f015E3F254fF18382D655B next.round=0 next.seq=13210 next.proposer=0xabC8508cE4cECfc03938c5E2ee181bE5578ed1DB next.valSet="[0x8D3827476c3854257D20dA89Cac6E644622910bF 0xB13c8245DE0a160B22A538DfCbce0ed053f0107D 0xa6Fb24E8311b540182f015E3F254fF18382D655B 0xabC8508cE4cECfc03938c5E2ee181bE5578ed1DB]" next.size=4 next.IsProposer=true
docker-compose-node01-1  | INFO [03-26|06:37:10.841] QBFT: handle block proposal request      address=0xabC8508cE4cECfc03938c5E2ee181bE5578ed1DB current.round=0 current.sequence=13210 state="Accept request"
docker-compose-node01-1  | INFO [03-26|06:37:10.841] EmptyBlockPeriod detected adding delay to request EmptyBlockPeriod=10 BlockTime=1,679,812,630
↓ this should not happen since the block number is 13209 (but sequence is 13210) and block hash is the previous one (e836b8..08ab71), not the current one (61e079..8e9191).
docker-compose-node01-1  | INFO [03-26|06:37:10.841] QBFT: broadcast PRE-PREPARE message      address=0xabC8508cE4cECfc03938c5E2ee181bE5578ed1DB current.round=0 current.sequence=13209 state=Committed        msg.code=18 msg.source=0xabC8508cE4cECfc03938c5E2ee181bE5578ed1DB msg.round=0 msg.sequence=13210 block.number=13209 block.hash=0xe836b8d56972f97206e719f1dd84e8f98a6127c73778011e3e205e773a08ab71 payload=0xf902ccf902c6f9028082339a80f90279f90274a0098828b5ef5d9f5c44e8575a00bf94cd1ccd09e78298917d4a06f2fd8107c48da01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d4934794abc8508ce4cecfc03938c5e2ee181be5578ed1dba0364b8d1f9f3c1404d15bbe78b47afada7da1297b3dd7d090f0b82ec79af6ab62a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018233998429b927008084641fe80db87cf87aa0d883010a03846765746888676f312e31392e35856c696e757800000000000000f854948d3827476c3854257d20da89cac6e644622910bf94a6fb24e8311b540182f015e3f254ff18382d655b94abc8508ce4cecfc03938c5e2ee181be5578ed1db94b13c8245de0a160b22a538dfcbce0ed053f0107dc080c0a063746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365880000000000000000c0c0b84139899b10cd5af6c2dbc7cf026bb54e0735844487095bc3a5991b116a938cd4f84d7ed885352923538501dfbcd7c62961c5e10af5adb2f075e9b850f94299c3e500c2c0c0
```
In this way the wrongly proposed block gets accepted and since its block number is the same as current block height, "chain reorg detected" log apeears on some node.
```
docker-compose-node01-1  | INFO [03-26|06:37:10.844] BFT: block proposal committed            author=0xabC8508cE4cECfc03938c5E2ee181bE5578ed1DB hash=e836b8..08ab71 number=13209
docker-compose-node01-1  | INFO [03-26|06:37:10.844] Chain reorg detected                     number=13208 hash=098828..07c48d drop=1 dropfrom=0f45db..a02097 add=1 addfrom=e836b8..08ab71
```
After this message, nodes get stuck at a round-change loop forever and no blocks will be produced.

#### Backtrace
no backtrace

[data.zip](https://github.com/ConsenSys/quorum/files/11071795/data.zip)
[node01.log](https://github.com/ConsenSys/quorum/files/11073427/node01.log)
[node02.log](https://github.com/ConsenSys/quorum/files/11073428/node02.log)
[node03.log](https://github.com/ConsenSys/quorum/files/11073425/node03.log)
[node04.log](https://github.com/ConsenSys/quorum/files/11073426/node04.log)

**Comment by YoshihitoAso** [comment]
Hello.

PR #1615, which directly fixes issue #1612, is not included in v22.7.6. So you should use the latest commit.

However, my understanding is that even though #1615 fixed it, the same issue would still occur, albeit much less frequently.
Unfortunately, my project doesn't use EmptyBlockPeriod, so I haven't experimented to reproduce the problem. Sorry if my understanding is wrong.

**Comment by hhsel** [comment]
Thank you for your comment and sorry for not being clear.
I encountered this problem before I found #1612, and I have applied the fix and am seeing if the problem still persists, though it is very difficult to reproduce deliberately, taking too much time even if it does.

After seeing #1612 (and the fix #1615), I think this fixes timing problems by synchronizing unnecessary asynchronous function calls, when `emptyblockperiodseconds` is turned off.
But I think this fix leave the other case untouched, because in https://github.com/ConsenSys/quorum/pull/1615/files#diff-b30bb83f420edfc24b653cf150ec55ef5d1acd6a9e459684ea0adef62bc14208R82 ,
as long as `emptyblockperiodseconds` is enabled, it goes through the `delay > 0` path and this is the same as before and the problem would still occur.
Now I am not confident whether I can safely enable `emptyblockperiodseconds`, which is why I post this issue.

Any corrections are appreciated.

**Comment by YoshihitoAso** [comment]
@hhsel, I have the same understanding.

There are still conditions to be processed asynchronously, and there is no exclusive control, so I think that the same problem can occur, although it occurs less frequently.

We don't use EmptyBlockPeriod in our production network ([ibet](https://github.com/BoostryJP/ibet-Network)), but if we do, we would like to use it after further verification of this point.

My understanding may be wrong. I would like to hear the main contributor's opinion, as there may be some intentions in the current implementation. @baptiste-b-pegasys @antonydenyer

> （日本語訳）私も同じ理解です。非同期で処理する条件が残っており、加えて排他制御を行なっていませんので、発生頻度は少ないものの同じ問題が発生し得るのではないかと私は思っています。私たちの運用中のネットワーク（ibet）では、EmptyBlockPeriodは利用していないのですが、利用する場合にはこの点をさらに検証した後に利用しようと考えていました。私の理解が間違っている可能性があります。現在の実装に何か意図があるかもしれませんので、主コントリビューターの見解を聞きたいところです。

**Comment by hhsel** [comment]
Now I have confirmed that even after applying the latest commits (to the current head of the `master` branch `b7476db3efe9dfcc0a12180657ee1f64b4e99f2d`), this still occurs.
It took 40329 blocks to happen, with `emptyblockperiodseconds=3` and `blockperiodseconds=1` .

So I think the current implementation is not safe to turn `emptyblockperiodseconds` on, the probability is very low but not marginal.

**Comment by antonydenyer** [comment]
> Now I have confirmed that even after applying the latest commits (to the current head of the `master` branch `b7476db3efe9dfcc0a12180657ee1f64b4e99f2d`), this still occurs. It took 40329 blocks to happen, with `emptyblockperiodseconds=3` and `blockperiodseconds=1` .
> 
> So I think the current implementation is not safe to turn `emptyblockperiodseconds` on, the probability is very low but not marginal.

Thanks @hhsel really appreciate the in-depth investigations. Could you confirm that all 4 nodes were running and healthy when the fork occurred?

**Comment by hhsel** [comment]
Attached here are the logs of the four nodes with their docker images built with the current head of the `master` branch `b7476db3efe9dfcc0a12180657ee1f64b4e99f2d`, block number ranging from 40325 to 40329, where the fork happened.

All nodes had been operating normally until the proposer of block number 40329 (node 3 in this case) wrongly proposed its previous mining work immediately after it became the proposer.
```
docker-compose-node03-1  | INFO [03-28|14:26:26.006] Commit new mining work                   number=40328 sealhash=707e36..c442a8 uncles=0 txs=0 gas=0 fees=0 elapsed="65.306µs"
...
docker-compose-node03-1  | INFO [03-28|14:26:29.006] Commit new mining work                   number=40329 sealhash=c2d96f..a7ab25 uncles=0 txs=0 gas=0 fees=0 elapsed="71.67µs"
docker-compose-node03-1  | INFO [03-28|14:26:29.006] QBFT: handle final committed             address=0x8D3827476c3854257D20dA89Cac6E644622910bF current.round=0 current.sequence=40328 state=Committed
docker-compose-node03-1  | INFO [03-28|14:26:29.006] QBFT: initialize new round               address=0x8D3827476c3854257D20dA89Cac6E644622910bF current.round=0 current.sequence=40328 target.round=0 lastProposal.number=40328 lastProposal.hash=c89da6..3c76aa
docker-compose-node03-1  | INFO [03-28|14:26:29.006] QBFT: changed state                      address=0x8D3827476c3854257D20dA89Cac6E644622910bF current.round=0 current.sequence=40329 old.state=Committed        new.state="Accept request"
docker-compose-node03-1  | INFO [03-28|14:26:29.006] QBFT: start new round                    address=0x8D3827476c3854257D20dA89Cac6E644622910bF old.round=0  old.sequence=40328 old.state=Committed        old.proposer=0xB13c8245DE0a160B22A538DfCbce0ed053f0107D next.round=0 next.seq=40329 next.proposer=0x8D3827476c3854257D20dA89Cac6E644622910bF next.valSet="[0x8D3827476c3854257D20dA89Cac6E644622910bF 0xa6Fb24E8311b540182f015E3F254fF18382D655B 0xabC8508cE4cECfc03938c5E2ee181bE5578ed1DB 0xB13c8245DE0a160B22A538DfCbce0ed053f0107D]" next.size=4 next.IsProposer=true
↓ this looks the same as I reported here before, broadcasting PRE-PREPARE message with the previous block number (40328) instead of the current one (40329)
docker-compose-node03-1  | INFO [03-28|14:26:29.006] QBFT: broadcast PRE-PREPARE message      address=0x8D3827476c3854257D20dA89Cac6E644622910bF current.round=0 current.sequence=40328 state=Committed        msg.code=18 msg.source=0x8D3827476c3854257D20dA89Cac6E644622910bF msg.round=0 msg.sequence=40329 block.number=40328 block.hash=0x987181119d364693c28683bf929ce0dd5ab46291a8630b071c5dfb35e342a6fc payload=0xf902ccf902c6f90280829d8980f90279f90274a01cf78ce80224b52093b7c7c302cedd7e51bddfc76da869fabf54cc02d730c8a6a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347948d3827476c3854257d20da89cac6e644622910bfa0364b8d1f9f3c1404d15bbe78b47afada7da1297b3dd7d090f0b82ec79af6ab62a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b901000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001829d888429b9270080846422f915b87cf87aa0d883010a03846765746888676f312e31392e37856c696e757800000000000000f854948d3827476c3854257d20da89cac6e644622910bf94a6fb24e8311b540182f015e3f254ff18382d655b94abc8508ce4cecfc03938c5e2ee181be5578ed1db94b13c8245de0a160b22a538dfcbce0ed053f0107dc080c0a063746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365880000000000000000c0c0b84164f6cd0d61e8a4be8ec08b926091e23eeeb6ed485ad448e015d1aef338142a510618e942c8f78b4d5760fe8fcc9b15d2edfc4ff7396c87212af02ab6b0bcd13401c2c0c0
...
docker-compose-node02-1  | INFO [03-28|14:26:29.008] BFT: block proposal committed            author=0xa6Fb24E8311b540182f015E3F254fF18382D655B hash=987181..42a6fc number=40328
docker-compose-node02-1  | INFO [03-28|14:26:29.009] Chain reorg detected                     number=40327 hash=1cf78c..30c8a6 drop=1 dropfrom=c89da6..3c76aa add=1 addfrom=987181..42a6fc
docker-compose-node02-1  | INFO [03-28|14:26:29.009] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed="759.178µs" mgasps=0.000 number=40328 hash=987181..42a6fc dirty=0.00B
```

I'm not sure why but it seems that at every block even non-proposers create blocks in their own and the moment when the `emptyblockperiodseonds` timer of the previous expires and when a new block mining work starts overlap for some reason, some kind of a race condition I guess.

[node01.log](https://github.com/ConsenSys/quorum/files/11096038/node01.log)
[node02.log](https://github.com/ConsenSys/quorum/files/11096039/node02.log)
[node03.log](https://github.com/ConsenSys/quorum/files/11096040/node03.log)
[node04.log](https://github.com/ConsenSys/quorum/files/11096041/node04.log)

**Comment by hhsel** [comment]
I updated container images to v23.4.0 and this still happened after ７６９２６　 blocks.

**Comment by hhsel** [comment]
Debug and trace level logs are available this time.

[node01.log](https://github.com/ConsenSys/quorum/files/11274919/node01.log)
[node02.log](https://github.com/ConsenSys/quorum/files/11274916/node02.log)
[node03.log](https://github.com/ConsenSys/quorum/files/11274917/node03.log)
[node04.log](https://github.com/ConsenSys/quorum/files/11274918/node04.log)

**Comment by hhsel** [comment]
I did some more analysis, and it seems that the fork happens at `preprepare.go:45`: 
https://github.com/Consensys/quorum/blob/fbfb5dd12a8c2b8abd053f858ef539ab38196b75/consensus/istanbul/qbft/core/preprepare.go#L40

All validator nodes do mining every block, whoever the proposer is.
Assuming the cluster keeps producing empty blocks with `emptyblockperiodseconds` enabled, when one of the validator nodes becomes the proposer at the block `N`, the block proposal request at the block `N-1` on the node after `emptyblockperiodseconds` arrives almost simultaneously in a asynchronous way.

Normally this proposal request of the block `N-1` is expected to be discarded, because
- the current sequence number has already progressed to `N` so `c.current.Sequence().Cmp()` is `false`
- the current sequence number has not progressed but the node is not the proposer at `N-1` so `c.IsProposer()` is `false`

A rare situation exists, however, where:
- When the `emptyblockperiodseconds` timer expires and the block proposal request at the block `N-1` is passed to `sendPreprepareMsg()`, `handleFinalCommitted()` has not been executed yet, so `c.current.Sequence().Cmp()` is `true`, because the current sequence number is still `N-1` on the node
- When determing `c.IsProposer()`, `handleFinalCommitted()` has been executed and `c.valSet` updated at `startNewRound()` so `c.IsProposer()` has become `true`

and the block proposal request at the block `N-1` is immediately proposed at the block `N`, when the node has become the proposer.

It seems that this can be caused deliberately, adding sleeps at `handleFinalCommitted()` and `IsProposer()` only to node 1 like https://github.com/hhsel/quorum/commit/bbf44d8c145fc7aafdc364f6ba67c7923f39e572 with the chain config, for example,
```
    "qbft": {
      "policy": 0,
      "epoch": 30000,
      "ceil2Nby3Block": 0,
      "testQBFTBlock": 0,
      "blockperiodseconds": 2,
      "emptyblockperiodseconds": 5,
      "requesttimeoutseconds": 4,
      "maxRequestTimeoutSeconds": 10
    }
```
almost immediately causes a chain fork.

I would suggest adding a mutex at these functions like https://github.com/hhsel/quorum/commit/6018d3339e50ceb078b36eb07f85a5f112554432, which at least has produced more than 10,000 blocks without problems in that extremely delayed situation.

**Comment by antonydenyer** [comment]
Agreed https://github.com/Consensys/quorum/pull/1669

Great stuff @hhsel thankyou for diligently working through the problem.

**Comment by hhsel** [comment]
@antonydenyer Now we have been able to operate the cluster with this option enabled for months without problems, but I recently notice that a malicious operator can yet run a node with extreme delay like I mentioned above intentionally, and other nodes are still susceptible to the wrong block and chain fork, leading to service dusruption anytime.

Should there be a stronger assumption and enforcement between QBFT request number and block number?

**Comment by antonydenyer** [comment]
>Should there be a stronger assumption and enforcement between QBFT request number and block number?

I'm not sure. I think it's fair to assume that you'd be using some sort of permissioning for your validators and would, therefore, vote them out if they misbehave. You could, in theory, use a smart contract to enforce some custom business logic.
