### ISSUE TITLE
Can we leverage Privacy Enhancements feature along with Privacy marker transactions (PMTs)? 

### ISSUE THREAD

**Issue by ghost** [ConsenSys/quorum#1680]
As we know that in addition to the [standard privacy (SP)](https://docs.goquorum.consensys.net/concepts/privacy/private-and-public#private-transactions), GoQuorum provides three kinds of privacy enhancements:

- [Counter-party protection](https://docs.goquorum.consensys.net/concepts/privacy/privacy-enhancements#counter-party-protection)
- [Mandatory party protection](https://docs.goquorum.consensys.net/concepts/privacy/privacy-enhancements#mandatory-party-protection)
- [Private state validation](https://docs.goquorum.consensys.net/concepts/privacy/privacy-enhancements#private-state-validation)

Can we use privacy enhancements, if we use privacy marker transactions (PMTs) instead of [normal private transactions](https://docs.goquorum.consensys.net/concepts/privacy/private-and-public#private-transactions)?

Is there any privacy enhancement feature offered natively with PMTs?

**Comment by SatpalSandhu61** [comment]
Yes, you can use all privacy enhancements even when using PMT's.

Assuming you have privacy enhancements and PMT's enabled on Tessera and GoQuorum.
Then when you send the private transaction, just set the privacy enhancement flag (`privacyFlag`) to the desired value.
