### ISSUE TITLE
Failed to deploy contract from locally created account

### ISSUE THREAD

**Issue by tsuzukit** [ConsenSys/quorum#344]
#### System information

Geth version: `geth version`
Version: 1.7.2-stable
Git Commit: ee498061b5a74bf1f3290139a53840345fa038cb
Quorum Version: 2.0.1

OS & Version: Windows/Linux/OSX
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"

Branch, Commit Hash or Release: `git status`

#### Expected behaviour

Ethereum account created locally via web3 can deploy public contract.

#### Actual behaviour

`Invalid sender` is returned from node. I sign the transaction with `web3.eth.accounts.signTransaction` and send Tx via `web3.eth.sendSignedTransaction`.
My networkid is 1234 and I have `conf.chainId:1234`  in my `genesis.json`.

#### Steps to reproduce the behaviour

1. Launch 7nodes vagrant container
2. ssh into container
3. Install nodejs and web3-1.0.0
4. modify `genesis.json` and `raft-start.sh` to use networkid of `1234` and EIP155 enabled
5. create small script to deploy contract to quorum node via JSON-RPC

```
const Web3 = require('web3');
const provider = new Web3.providers.HttpProvider("http://localhost:22001");
const web3 = new Web3(provider);

let account = web3.eth.accounts.create();

// same abi as script1.js
var abi = [{"constant":true,"inputs":[], ...}];

// same bytecode as script1.js
var bytecode = "0x60606040...";

var contract = new web3.eth.Contract(abi);

deploy = async () => {

  const data = contract.deploy({ data: bytecode, arguments: [42] }).encodeABI();
  const transactionObject = {
    gas: "5000000",
    data: data,
    from: account.address,
  };

  try {
    // this looks good and `v` parameter looks properly encoded too.
    const signedTransaction = await web3.eth.accounts.signTransaction(transactionObject, account.privateKey);
    console.log(signedTransaction);

    // this returns an error
    const result = await web3.eth.sendSignedTransaction(signedTransaction.rawTransaction);
    console.log(result);
  }
  catch (err) {
    console.log(err);
  }

};
deploy();
```

* This [commit in forked repo](https://github.com/tsuzukit/quorum-examples/commit/46c79f4849572ff7162412b7fac5a830be3fd326) is to crate above setup 

#### Backtrace

````
[backtrace]
````

**Comment by tsuzukit** [comment]
@jpmsam 
Hi, 
I think I found what went wrong and I wonder if it is OK to make a Pull request?

**Comment by jpmsam** [comment]
@tsuzukit Sure, please do.

**Comment by tsuzukit** [comment]
@jpmsam 
Thank you!
https://github.com/jpmorganchase/quorum/pull/350 is the PR and please review.

**Comment by jpmsam** [comment]
@tsuzukit thanks for the PR. I have merged it and we have made some updates to our reference quorum-examples repo.
