### ISSUE TITLE
who to add some new validators after the block init.

### ISSUE THREAD

**Issue by yacc2007** [ConsenSys/quorum#386]
when I make the private chain with the init genesis.json and set the extaData so it means set the fixed validators, but if the chain cluster run after a long time, I want to update the chain cluster, add some new validators, who can I do that? at this scene, I can't modify the genesis.json's extaData and re do init block data.

**Comment by jpmsam** [comment]
@yacc2007 Please reference the [instructions](https://medium.com/getamis/istanbul-bft-ibft-c2758b7fe6ff) under Add/Remove from AMIS.
