### ISSUE TITLE
Raft consensus + Solidity: require, assert and revert are not working properly.

### ISSUE THREAD

**Issue by ghost** [ConsenSys/quorum#402]
#### System information

Geth version: 1.7.2-stable
Quorum Version: 2.0.1

Expected behaviour
It should raise an exception and revert the transaction when a call is made by another user which is not an owner of the contract.

Actual behaviour
It is not raising exception nor reverting the transaction. Instead, it allowing to make a transaction and returns nothing.

**Comment by jpmsam** [comment]
Please reference the latest genesis block from Quorum examples and start a new network to test it.

**Comment by ghost** [comment]
Just replace genesis.json? 
Is it necessary to update my quorum?

Now only in the truffle effect, if `web3.contract(abi).at(address)` way is still not.

**Comment by jpmsam** [comment]
> Just replace genesis.json?

You should test on a new network.
>Is it necessary to update my quorum?

I suggest running master since it has some other fixes.
